// Code generated by metago; DO NOT EDIT.

package mock

type MockStore struct {
	GetFunc  func(id string) (User, error)
	SaveFunc func(user User) error
}

func (m *MockStore) Get(id string) (User, error) {
	return m.GetFunc(id)
}

func (m *MockStore) Save(user User) error {
	return m.SaveFunc(user)
}
