// Code generated by metago; DO NOT EDIT.

package stringer

import (
	"strconv"
)

func (v Priority) String() string {
	switch v {
	case PriorityLow:
		return "Low"
	case PriorityNormal:
		return "Normal"
	case PriorityHigh:
		return "High"
	default:
		return "Priority(" + strconv.FormatInt(int64(v), 10) + ")"
	}
}

func (v Direction) String() string {
	switch v {
	case DirectionUnknown:
		return "Unknown"
	case DirectionNorth:
		return "North"
	case DirectionSouth:
		return "South"
	default:
		return "Direction(" + strconv.FormatInt(int64(v), 10) + ")"
	}
}

func (v Permission) String() string {
	switch v {
	case PermissionRead:
		return "Read"
	case PermissionWrite:
		return "Write"
	case PermissionAdmin:
		return "Admin"
	default:
		return "Permission(" + strconv.FormatUint(uint64(v), 10) + ")"
	}
}

func (v State) String() string {
	switch v {
	case StateReady:
		return "Ready"
	case StateBusy:
		return "Busy"
	default:
		return "State(" + strconv.Quote(string(v)) + ")"
	}
}

func (v Enabled) String() string {
	switch v {
	case EnabledNo:
		return "No"
	case EnabledYes:
		return "Yes"
	default:
		return "Enabled(" + strconv.FormatBool(bool(v)) + ")"
	}
}

func (v Ratio) String() string {
	switch v {
	case RatioHalf:
		return "Half"
	case RatioFull:
		return "Full"
	default:
		return "Ratio(" + strconv.FormatFloat(float64(v), 'g', -1, 64) + ")"
	}
}

func (v Phase) String() string {
	switch v {
	case PhaseReal:
		return "Real"
	case PhaseImaginary:
		return "Imaginary"
	default:
		return "Phase(" + strconv.FormatComplex(complex128(v), 'g', -1, 128) + ")"
	}
}

func (v Label) String() string {
	return string(v)
}

func (v Count) String() string {
	return strconv.FormatInt(int64(v), 10)
}

func (v UCount) String() string {
	return strconv.FormatUint(uint64(v), 10)
}

func (v Flag) String() string {
	return strconv.FormatBool(bool(v))
}

func (v Score) String() string {
	return strconv.FormatFloat(float64(v), 'g', -1, 64)
}

func (v Point) String() string {
	return strconv.FormatComplex(complex128(v), 'g', -1, 128)
}
