package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Typed const blocks using iota carry the type to later specs, so enum values include every
// member, skip blank identifiers, and ignore untyped consts.
func TestIotaConstValues(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen enum Color

type Color int

const (
	Red Color = iota
	Green
	Blue
	_
	limit
)

const (
	debug          = true
	Fallback Color = 0
)

const Loose = "untyped consts never attach"
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "enum" }}
const ColorNames = "{{ range .Values }}{{ .Name }}={{ .Value }};{{ end }}"
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst ColorNames = \"Red=iota;Green=iota;Blue=iota;limit=iota;Fallback=0;\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// Typed consts attach to their type regardless of declaration order: the const block lives in a
// file that is scanned before the file declaring the type.
func TestConstValuesAttachRegardlessOfDeclarationOrder(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "a.go"), `package fixture

const (
	Active   Status = "active"
	Disabled Status = "disabled"
)
`)
	writeTestFile(t, filepath.Join(dir, "z.go"), `package fixture

//mgo:gen enum Status

type Status string
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "enum" }}
const StatusNames = "{{ range .Values }}{{ .Name }},{{ end }}"
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst StatusNames = \"Active,Disabled,\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// A fresh //mgo:inline without //mgo:end must not bind to the //mgo:end of a later annotation; that would wipe
// every declaration between the two annotations.
func TestInlineEndBindsToOwnMeta(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

type A string

//mgo:inline stringer A

type B string

//mgo:inline stringer B

func (b B) String() string { return string(b) }

//mgo:end
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func ({{ receiver . }} {{ name . }}) String() string { return string({{ receiver . }}) }
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	want := `package fixture

type A string

//mgo:inline stringer A

func (a A) String() string { return string(a) }

//mgo:end

type B string

//mgo:inline stringer B

func (b B) String() string { return string(b) }

//mgo:end
`
	if got != want {
		t.Fatalf("inline output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestMultipleInlineMetasInOneFile(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

type A string

//mgo:inline stringer A

type B string

//mgo:inline stringer B
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func ({{ receiver . }} {{ name . }}) String() string { return string({{ receiver . }}) }
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	want := `package fixture

type A string

//mgo:inline stringer A

func (a A) String() string { return string(a) }

//mgo:end

type B string

//mgo:inline stringer B

func (b B) String() string { return string(b) }

//mgo:end
`
	if got != want {
		t.Fatalf("inline output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// Stale generated code between //mgo:inline and //mgo:end is replaced, not appended to.
func TestInlineReplacesStaleBlock(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

type A string

//mgo:inline stringer A

func (a A) OldGenerated() string { return "stale" }

//mgo:end
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func ({{ receiver . }} {{ name . }}) String() string { return string({{ receiver . }}) }
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	want := `package fixture

type A string

//mgo:inline stringer A

func (a A) String() string { return string(a) }

//mgo:end
`
	if got != want {
		t.Fatalf("inline output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// Switching an existing inline directive to gen removes the old inline body and marker while
// moving freshly generated output to the package sidecar.
func TestGenRemovesStaleInlineBlock(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

//mgo:gen stringer
type A string

func (a A) String() string { return "stale" }

//mgo:end
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func ({{ receiver . }} {{ name . }}) String() string { return string({{ receiver . }}) }
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	wantModel := `package fixture

//mgo:gen stringer
type A string

`
	if got := string(files[model]); got != wantModel {
		t.Fatalf("cleaned source mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, wantModel)
	}
	sidecar := string(files[filepath.Join(dir, "meta.go")])
	if !strings.Contains(sidecar, "func (a A) String() string { return string(a) }") {
		t.Fatalf("sidecar output mismatch:\n%s", sidecar)
	}
}

// Writing the inline output back and regenerating produces the same file.
func TestInlineRegenerationIsIdempotent(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

type A string

//mgo:inline stringer A

type B string

//mgo:inline stringer B
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func ({{ receiver . }} {{ name . }}) String() string { return string({{ receiver . }}) }
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	first := files[model]
	if err := os.WriteFile(model, first, 0644); err != nil {
		t.Fatal(err)
	}

	files, err = generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	second := files[model]
	if string(second) != string(first) {
		t.Fatalf("regeneration is not idempotent\n\n--- first ---\n%s\n--- second ---\n%s", first, second)
	}
}

func TestInlineImportsMergeIntoExistingImports(t *testing.T) {
	template := `{{ define "stringer" }}
{{ imports "strconv" }}
func (a {{ name . }}) String() string { return strconv.Itoa(int(a)) }
{{ end }}
`
	want := `package fixture

import (
	"fmt"
	"strconv"
)

type A int

//mgo:inline stringer A

func (a A) String() string { return strconv.Itoa(int(a)) }

//mgo:end

var _ = fmt.Sprint
`
	cases := map[string]string{
		"paren import block": `package fixture

import (
	"fmt"
)

type A int

//mgo:inline stringer A

var _ = fmt.Sprint
`,
		"single-line import": `package fixture

import "fmt"

type A int

//mgo:inline stringer A

var _ = fmt.Sprint
`,
	}
	for name, source := range cases {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			model := filepath.Join(dir, "model.go")
			writeTestFile(t, model, source)
			writeTestFile(t, filepath.Join(dir, "templates.metago"), template)

			files, err := generateFiles(dir)
			if err != nil {
				t.Fatal(err)
			}
			got := string(files[model])
			if got != want {
				t.Fatalf("inline output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
			}
		})
	}
}

func TestInlineImportAlreadyPresentIsNotDuplicated(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

import "strconv"

type A int

//mgo:inline stringer A

var _ = strconv.Itoa
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
{{ imports "strconv" }}
func (a {{ name . }}) String() string { return strconv.Itoa(int(a)) }
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	want := `package fixture

import "strconv"

type A int

//mgo:inline stringer A

func (a A) String() string { return strconv.Itoa(int(a)) }

//mgo:end

var _ = strconv.Itoa
`
	if got != want {
		t.Fatalf("inline output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// Methods declared on generic receivers attach to their type; ReceiverType keeps type parameters.
func TestGenericReceiverMethods(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary Stack

type Stack[T any] struct {
	items []T
}

func (s *Stack[T]) Push(item T) { s.items = append(s.items, item) }

func (s Stack[T]) Len() int { return len(s.items) }

type Pair[K comparable, V any] struct{}

func (p Pair[K, V]) Key() K { var k K; return k }
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Summary = {{ quote (printf "methods=%s recv0=%s pair=%s" (methodNames .) (index .Methods 0).ReceiverType (methodNames (index .Package.Types 1))) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"methods=Push,Len recv0=*Stack[T] pair=Key\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// Documents a known limitation: embedded interfaces contribute no methods to .Methods.
func TestEmbeddedInterfaceMethodsAreIgnored(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary ReadCloser

type Reader interface {
	Read() error
}

type ReadCloser interface {
	Reader
	Close() error
}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Summary = {{ quote (methodNames .) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"Close\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// Meta comments trailing a declaration on the same line work like any other //mgo:gen comment.
func TestTrailingMetaCommentOnDeclarationLine(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

type Status string //mgo:gen stringer Status
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (x {{ name . }}) String() string { return string(x) }
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nfunc (x Status) String() string { return string(x) }\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// A targetless annotation binds to the nearest declaration by line distance, above or below,
// choosing between types and functions.
func TestTargetlessMetaBindsToNearestDeclaration(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen describe
type First string

//mgo:gen describe
func Helper() {}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "describe" }}
const {{ name . }}Kind = {{ quote .Kind }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst FirstKind = \"type\"\n\nconst HelperKind = \"function\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestUnknownTemplateErrorIncludesLocation(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen nope Status

type Status string
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (x {{ name . }}) String() string { return string(x) }
{{ end }}
`)

	_, err := generate(dir)
	if err == nil {
		t.Fatal("expected unknown template error")
	}
	if !strings.Contains(err.Error(), `execute template "nope"`) || !strings.Contains(err.Error(), "model.go:3") {
		t.Fatalf("expected template name and file:line in error, got: %v", err)
	}
}

func TestStandardTemplateWorksWithoutTemplateFiles(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen std.stringer
type Status string

const Ready Status = "ready"
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatalf("generate with embedded standard template: %v", err)
	}
	if !strings.Contains(string(got), "func (v Status) String() string") {
		t.Fatalf("embedded std.stringer output missing String method:\n%s", got)
	}
}

func TestStandardSerdeJSONDefaultsToLocalRuntime(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen std.serde.jsonruntime
type Runtime struct{}

//mgo:gen std.serde.json
type User struct {
	Name string `+"`json:\"name\"`"+`
}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatalf("generate local std.serde.json runtime: %v", err)
	}
	source := string(got)
	for _, want := range []string{
		"type Lexer struct",
		"AppendString(b, string(v.Name))",
		"Lexer{Data: data}",
	} {
		if !strings.Contains(source, want) {
			t.Errorf("generated local-runtime path missing %q", want)
		}
	}
	if strings.Contains(source, "serdejsonruntime") {
		t.Errorf("local-runtime codec unexpectedly imports a shared runtime:\n%s", source)
	}
}

func TestUnknownTargetErrors(t *testing.T) {
	template := `{{ define "describe" }}
const Name = {{ quote .Name }}
{{ end }}
`
	cases := map[string]struct {
		model string
		want  string
	}{
		"missing method": {
			model: "package fixture\n\n//mgo:gen describe User.Nope\n\ntype User struct{}\n",
			want:  `unknown meta target "User.Nope"`,
		},
		"missing type": {
			model: "package fixture\n\n//mgo:gen describe Ghost\n\ntype User struct{}\n",
			want:  `unknown meta target "Ghost"`,
		},
		"no declarations for targetless meta": {
			model: "package fixture\n\n//mgo:gen describe\n",
			want:  `unknown meta target ""`,
		},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			writeTestFile(t, filepath.Join(dir, "model.go"), tc.model)
			writeTestFile(t, filepath.Join(dir, "templates.metago"), template)

			_, err := generate(dir)
			if err == nil {
				t.Fatal("expected unknown target error")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("expected %q in error, got: %v", tc.want, err)
			}
		})
	}
}

func TestSidecarAliasedImports(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen jsonname User

type User struct {
	ID int
}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "jsonname" }}
{{ imports "encoding/json" "stdjson" }}
func {{ name . }}JSON(v {{ name . }}) ([]byte, error) { return stdjson.Marshal(v) }
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nimport (\n\tstdjson \"encoding/json\"\n)\n\nfunc UserJSON(v User) ([]byte, error) { return stdjson.Marshal(v) }\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestParseMetaEdgeCases(t *testing.T) {
	if _, err := parseMeta("", "f.go", 1, false); err == nil {
		t.Fatal("empty meta directive should error")
	}

	meta, err := parseMeta("tmpl", "f.go", 1, false)
	if err != nil || meta.Target != "" || len(meta.Args) != 0 || len(meta.Argv) != 0 {
		t.Fatalf("bare template meta = %#v err = %v", meta, err)
	}

	// A leading key=value means no target; later bare words become positional args.
	meta, err = parseMeta("tmpl key=value pos", "f.go", 1, false)
	if err != nil || meta.Target != "" || meta.Args["key"] != "value" || len(meta.Argv) != 1 || meta.Argv[0] != "pos" {
		t.Fatalf("targetless meta = %#v err = %v", meta, err)
	}

	// Gotcha: the first bare word is always the target, never a positional arg.
	meta, err = parseMeta("tmpl users public", "f.go", 1, false)
	if err != nil || meta.Target != "users" || len(meta.Argv) != 1 || meta.Argv[0] != "public" {
		t.Fatalf("bare word meta = %#v err = %v", meta, err)
	}

	meta, err = parseMeta("tmpl User key=", "f.go", 1, false)
	if err != nil || meta.Target != "User" || meta.Args["key"] != "" {
		t.Fatalf("empty value meta = %#v err = %v", meta, err)
	}
	if _, exists := meta.Args["key"]; !exists {
		t.Fatal("empty key=value should still register the key")
	}

	// A URL-path-like first token is a positional arg, never a target, so decorator-style
	// annotations like //mgo:gen get /posts/{postID} bind to the nearest declaration.
	meta, err = parseMeta("get /posts/{postID}", "f.go", 1, false)
	if err != nil || meta.Target != "" || len(meta.Argv) != 1 || meta.Argv[0] != "/posts/{postID}" {
		t.Fatalf("path positional meta = %#v err = %v", meta, err)
	}

	// An explicit target still combines with a path positional.
	meta, err = parseMeta("get PostRoutes.Show /posts/{postID}", "f.go", 1, false)
	if err != nil || meta.Target != "PostRoutes.Show" || len(meta.Argv) != 1 || meta.Argv[0] != "/posts/{postID}" {
		t.Fatalf("target plus path meta = %#v err = %v", meta, err)
	}

	// Import-path targets contain a slash but never lead with one, so they stay targets.
	meta, err = parseMeta("describe net/http.Client", "f.go", 1, false)
	if err != nil || meta.Target != "net/http.Client" || len(meta.Argv) != 0 {
		t.Fatalf("import path target meta = %#v err = %v", meta, err)
	}

	// A token containing braces is positional even without a leading slash.
	meta, err = parseMeta("get posts/{postID}", "f.go", 1, false)
	if err != nil || meta.Target != "" || len(meta.Argv) != 1 || meta.Argv[0] != "posts/{postID}" {
		t.Fatalf("brace positional meta = %#v err = %v", meta, err)
	}

	// Anchored (doc-position) directives never consume a target: every bare token is positional,
	// because the target is the symbol the directive is written on.
	meta, err = parseMeta("tmpl users public speed=fast", "f.go", 1, true)
	if err != nil || meta.Target != "" || len(meta.Argv) != 2 || meta.Argv[0] != "users" || meta.Argv[1] != "public" || meta.Args["speed"] != "fast" {
		t.Fatalf("anchored meta = %#v err = %v", meta, err)
	}
}

// Grouped declarations expand: `First, Last string` yields two fields sharing type and tag,
// `Do(a, b int)` yields two params.
func TestGroupedFieldsAndParams(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User

type User struct {
	First, Last string `+"`json:\"name\"`"+`
}

func (u User) Do(a, b int) {}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Summary = {{ quote (printf "fields=%s tags=%s/%s params=%s:%s,%s:%s" (join (fieldNames .) ",") (tag (index .Fields 0) "json") (tag (index .Fields 1) "json") (index (index .Methods 0).Params 0).Name (index (index .Methods 0).Params 0).Type (index (index .Methods 0).Params 1).Name (index (index .Methods 0).Params 1).Type) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"fields=First,Last tags=name/name params=a:int,b:int\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}
