package main

import (
	"path/filepath"
	"strings"
	"testing"
)

// Every //mgo: comment must be a well-formed directive; typos error instead of silently no-oping.
func TestInvalidDirectivesError(t *testing.T) {
	template := `{{ define "stringer" }}
func (x {{ name . }}) String() string { return string(x) }
{{ end }}
`
	cases := map[string]struct {
		model string
		want  string
	}{
		"unknown verb": {
			model: "package fixture\n\n//mgo:stringer Status\ntype Status string\n",
			want:  `invalid //mgo: directive "//mgo:stringer Status"`,
		},
		"empty directive": {
			model: "package fixture\n\n//mgo:\ntype Status string\n",
			want:  `invalid //mgo: directive "//mgo:"`,
		},
		"gen without template name": {
			model: "package fixture\n\n//mgo:gen\ntype Status string\n",
			want:  "missing a template name",
		},
		"inline without template name": {
			model: "package fixture\n\n//mgo:inline\ntype Status string\n",
			want:  "missing a template name",
		},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			writeTestFile(t, filepath.Join(dir, "model.go"), tc.model)
			writeTestFile(t, filepath.Join(dir, "templates.metago"), template)

			_, err := generate(dir)
			if err == nil {
				t.Fatal("expected invalid directive error")
			}
			if !strings.Contains(err.Error(), tc.want) || !strings.Contains(err.Error(), "model.go:3") {
				t.Fatalf("expected %q and model.go:3 in error, got: %v", tc.want, err)
			}
		})
	}
}

// //mgo:end alone is a marker, not an annotation, and never errors.
func TestEndDirectiveAloneIsIgnored(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), "package fixture\n\n//mgo:end\ntype Status string\n")
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}x{{ end }}`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 0 {
		t.Fatalf("stray //mgo:end should generate nothing, got:\n%s", got)
	}
}

// An //mgo:end with trailing whitespace still terminates its inline block; otherwise regeneration
// would insert a duplicate block above the stale marker.
func TestEndDirectiveToleratesTrailingWhitespace(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, "package fixture\n\ntype A string\n\n//mgo:inline stringer A\n\nfunc (a A) Old() string { return \"stale\" }\n\n//mgo:end \n")
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (a {{ name . }}) String() string { return string(a) }
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	if strings.Contains(got, "Old()") {
		t.Fatalf("stale block should be replaced despite trailing space on //mgo:end, got:\n%s", got)
	}
	if strings.Count(got, "String()") != 1 {
		t.Fatalf("generated block should appear exactly once, got:\n%s", got)
	}
}

// Tabs work as separators between the verb and its arguments.
func TestDirectiveToleratesTabSeparators(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), "package fixture\n\n//mgo:gen\tstringer Status\ntype Status string\n")
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (x {{ name . }}) String() string { return string(x) }
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nfunc (x Status) String() string { return string(x) }\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// //mgo:end never takes arguments; trailing content is a typo worth surfacing.
func TestEndDirectiveWithArgumentsErrors(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), "package fixture\n\n//mgo:end now\ntype Status string\n")
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}x{{ end }}`)

	_, err := generate(dir)
	if err == nil {
		t.Fatal("expected end-with-arguments error")
	}
	if !strings.Contains(err.Error(), "//mgo:end takes no arguments") || !strings.Contains(err.Error(), "model.go:3") {
		t.Fatalf("expected end arguments error with location, got: %v", err)
	}
}

func TestPropsRequireGroupName(t *testing.T) {
	cases := map[string]string{
		"bare":              "package fixture\n\n//mgo:props\ntype Status string\n",
		"leading key=value": "package fixture\n\n//mgo:props max=10\ntype Status string\n",
	}
	for name, model := range cases {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			writeTestFile(t, filepath.Join(dir, "model.go"), model)
			writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}x{{ end }}`)

			_, err := generate(dir)
			if err == nil {
				t.Fatal("expected missing group error")
			}
			if !strings.Contains(err.Error(), "//mgo:props requires a group name") || !strings.Contains(err.Error(), "model.go:3") {
				t.Fatalf("expected group name error with location, got: %v", err)
			}
		})
	}
}

func TestPropsWithoutSymbolErrors(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), "package fixture\n\n//mgo:props validate required\n")
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}x{{ end }}`)

	_, err := generate(dir)
	if err == nil {
		t.Fatal("expected no symbol error")
	}
	if !strings.Contains(err.Error(), "has no symbol to attach to") || !strings.Contains(err.Error(), "model.go:3") {
		t.Fatalf("expected attach error with location, got: %v", err)
	}
}

// Props attach to the nearest symbol in the same file: types, fields (doc and trailing position),
// methods, functions, interface methods, and embedded fields.
func TestPropsAttachToSymbols(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User

//mgo:props api owner=core
type User struct {
	//mgo:props validate required max=2000
	Text string

	Rating int //mgo:props validate min=1 max=5

	//mgo:props flatten
	Base
}

type Base struct{}

//mgo:props route member
func (u User) Show() {}

//mgo:props job cron=daily
func Cleanup() {}

type Store interface {
	//mgo:props scope admin
	Delete(id string) error
}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
{{- $store := index .Package.Types 2 -}}
{{- $cleanup := index .Package.Functions 0 -}}
const Summary = {{ quote (printf "type=%s text_req=%t text_max=%s rating_min=%s rating_max=%s base=%t method=%t fn=%s iface=%t"
	(prop . "api" "owner")
	(propHas (index .Fields 0) "validate" "required")
	(prop (index .Fields 0) "validate" "max")
	(prop (index .Fields 1) "validate" "min")
	(prop (index .Fields 1) "validate" "max")
	(propExists (index .Fields 2) "flatten")
	(propHas (index .Methods 0) "route" "member")
	(prop $cleanup "job" "cron")
	(propHas (index $store.Methods 0) "scope" "admin")) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"type=core text_req=true text_max=2000 rating_min=1 rating_max=5 base=true method=true fn=daily iface=true\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// The flatten group has no key=value args but exists; propExists distinguishes that from absent
// groups, and bare flags are matched by propHas.
func TestPropsFlagsAndExistence(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User

type User struct {
	//mgo:props pii
	Email string
}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Summary = {{ quote (printf "pii=%t missing=%t flag=%t missing_key=%q" (propExists (index .Fields 0) "pii") (propExists (index .Fields 0) "nope") (propHas (index .Fields 0) "pii" "pii") (prop (index .Fields 0) "nope" "key")) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"pii=true missing=false flag=false missing_key=\\\"\\\"\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// Multiple //mgo:props lines on one symbol: distinct groups stay separate; duplicate groups merge
// with flags unioned and later keys winning.
func TestPropsGroupsMergeAndStack(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User

type User struct {
	//mgo:props validate required max=100
	//mgo:props validate required max=200 min=1
	//mgo:props db column=email_addr
	Email string
}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
{{- $email := index .Fields 0 -}}
const Summary = {{ quote (printf "max=%s min=%s flags=%s column=%s" (prop $email "validate" "max") (prop $email "validate" "min") (join (props $email "validate").Argv ",") (prop $email "db" "column")) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"max=200 min=1 flags=required column=email_addr\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// A props line equidistant between two fields attaches to the one below, matching Go's
// doc-comment convention.
func TestPropsEquidistantPrefersSymbolBelow(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User

type User struct {
	Above string
	//mgo:props g here
	Below string
}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Summary = {{ quote (printf "above=%t below=%t" (propHas (index .Fields 0) "g" "here") (propHas (index .Fields 1) "g" "here")) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"above=false below=true\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// Props attach per file: a symbol on a nearby line in another file must not capture them.
func TestPropsAttachWithinOwnFileOnly(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "a.go"), `package fixture

//mgo:props g mine
type A string
`)
	writeTestFile(t, filepath.Join(dir, "z.go"), `package fixture

//mgo:gen summary B

type B string
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
{{- $a := index .Package.Types 0 -}}
const Summary = {{ quote (printf "a=%t b=%t" (propHas $a "g" "mine") (propHas .Type "g" "mine")) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"a=true b=false\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// prop helpers are nil-safe on symbols without any props.
func TestPropHelpersNilSafety(t *testing.T) {
	field := Field{Name: "Plain"}
	if propValue(field, "g", "k") != "" {
		t.Fatal("prop on propless field should be empty")
	}
	if propHasFlag(field, "g", "flag") {
		t.Fatal("propHas on propless field should be false")
	}
	if propGroupExists(field, "g") {
		t.Fatal("propExists on propless field should be false")
	}
	if group := propGroup(field, "g"); group.Group != "" || len(group.Args) != 0 || len(group.Argv) != 0 {
		t.Fatalf("props on propless field should be zero, got %#v", group)
	}
	if propsOf(nil) != nil {
		t.Fatal("propsOf(nil) should be nil")
	}
	if propValue("not a symbol", "g", "k") != "" {
		t.Fatal("prop on non-symbol should be empty")
	}
}

// propsOf resolves through invocations to the targeted method, function, or type.
func TestPropsVisibleThroughInvocation(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:props api version=2
type User struct{}

//mgo:gen describe User
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "describe" }}
const Version = {{ quote (prop . "api" "version") }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Version = \"2\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// One aggregator annotation can read every annotation in the package via .Package.Metas, in
// deterministic file-then-line order, with args, argv, and location. Props metas attach to
// symbols instead and never appear there. This is the primitive for many-annotations-one-artifact
// generators such as HTTP route tables.
func TestPackageMetasAggregation(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "a.go"), `package fixture

//mgo:gen get /posts/{postID} auth=required
func ShowPost() {}

//mgo:props internal flag
type helper struct{}
`)
	writeTestFile(t, filepath.Join(dir, "b.go"), `package fixture

//mgo:gen post /posts
func CreatePost() {}

//mgo:gen server
type Server struct{}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "get" }}{{ end }}
{{ define "post" }}{{ end }}
{{ define "server" }}
const Routes = {{ quote (printf "%s" .Package.Metas) }}
const Table = "
{{- range .Package.Metas }}
{{- if or (eq .Template "get") (eq .Template "post") }}
{{- upper .Template }} {{ index .Argv 0 }} auth={{ index .Args "auth" }};
{{- end }}
{{- end }}"
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	output := string(got)
	if !strings.Contains(output, `const Table = "GET /posts/{postID} auth=required;POST /posts auth=;"`) {
		t.Fatalf("aggregated route table mismatch, got:\n%s", output)
	}
	if strings.Contains(output, "props") || strings.Contains(output, "internal") {
		t.Fatalf("props metas must not appear in .Package.Metas, got:\n%s", output)
	}
}

// The aggregator sees inline annotations too, marked with Inline.
func TestPackageMetasIncludeInlineAnnotations(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

type A string

//mgo:inline stringer A

//mgo:gen summary A
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (a {{ name . }}) String() string { return string(a) }
{{ end }}
{{ define "summary" }}
const Summary = {{ quote (printf "%d" (len .Package.Metas)) }}
{{- range .Package.Metas }}{{ if .Inline }}
const InlineTemplate = {{ quote .Template }}
{{- end }}{{ end }}
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	sidecar := string(files[filepath.Join(dir, "meta.go")])
	if !strings.Contains(sidecar, `const Summary = "2"`) || !strings.Contains(sidecar, `const InlineTemplate = "stringer"`) {
		t.Fatalf("expected inline meta in .Package.Metas, got:\n%s", sidecar)
	}
}
