package main

import (
	"path/filepath"
	"strings"
	"testing"
)

// Reserved directives must be well formed; other namespaces are symbol properties.
func TestInvalidDirectivesError(t *testing.T) {
	template := `{{ define "stringer" }}
func (x {{ name . }}) String() string { return string(x) }
{{ end }}
`
	cases := map[string]struct {
		model string
		want  string
	}{
		"empty directive": {
			model: "package fixture\n\n//mgo:\ntype Status string\n",
			want:  "property directive is missing a namespace",
		},
		"gen without template name": {
			model: "package fixture\n\n//mgo:gen\ntype Status string\n",
			want:  "missing a template name",
		},
		"inline without template name": {
			model: "package fixture\n\n//mgo:inline\ntype Status string\n",
			want:  "missing a template name",
		},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			writeTestFile(t, filepath.Join(dir, "model.go"), tc.model)
			writeTestFile(t, filepath.Join(dir, "templates.metago"), template)

			_, err := generate(dir)
			if err == nil {
				t.Fatal("expected invalid directive error")
			}
			if !strings.Contains(err.Error(), tc.want) || !strings.Contains(err.Error(), "model.go:3") {
				t.Fatalf("expected %q and model.go:3 in error, got: %v", tc.want, err)
			}
		})
	}
}

// //mgo:end alone is a marker, not an annotation, and never errors.
func TestEndDirectiveAloneIsIgnored(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), "package fixture\n\n//mgo:end\ntype Status string\n")
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}x{{ end }}`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 0 {
		t.Fatalf("stray //mgo:end should generate nothing, got:\n%s", got)
	}
}

// An //mgo:end with trailing whitespace still terminates its inline block; otherwise regeneration
// would insert a duplicate block above the stale marker.
func TestEndDirectiveToleratesTrailingWhitespace(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, "package fixture\n\ntype A string\n\n//mgo:inline stringer A\n\nfunc (a A) Old() string { return \"stale\" }\n\n//mgo:end \n")
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (a {{ name . }}) String() string { return string(a) }
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	if strings.Contains(got, "Old()") {
		t.Fatalf("stale block should be replaced despite trailing space on //mgo:end, got:\n%s", got)
	}
	if strings.Count(got, "String()") != 1 {
		t.Fatalf("generated block should appear exactly once, got:\n%s", got)
	}
}

// Tabs work as separators between the verb and its arguments.
func TestDirectiveToleratesTabSeparators(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), "package fixture\n\n//mgo:gen\tstringer Status\ntype Status string\n")
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (x {{ name . }}) String() string { return string(x) }
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nfunc (x Status) String() string { return string(x) }\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// //mgo:end never takes arguments; trailing content is a typo worth surfacing.
func TestEndDirectiveWithArgumentsErrors(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), "package fixture\n\n//mgo:end now\ntype Status string\n")
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}x{{ end }}`)

	_, err := generate(dir)
	if err == nil {
		t.Fatal("expected end-with-arguments error")
	}
	if !strings.Contains(err.Error(), "//mgo:end takes no arguments") || !strings.Contains(err.Error(), "model.go:3") {
		t.Fatalf("expected end arguments error with location, got: %v", err)
	}
}

func TestPropertyNamespaceCannotBeKeyValue(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), "package fixture\n\n//mgo:max=10\ntype Status string\n")
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}x{{ end }}`)

	_, err := generate(dir)
	if err == nil {
		t.Fatal("expected invalid namespace error")
	}
	if !strings.Contains(err.Error(), `invalid property namespace "max=10"`) || !strings.Contains(err.Error(), "model.go:3") {
		t.Fatalf("expected namespace error with location, got: %v", err)
	}
}

func TestPropsWithoutSymbolErrors(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), "package fixture\n\n//mgo:validate required\n")
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}x{{ end }}`)

	_, err := generate(dir)
	if err == nil {
		t.Fatal("expected no symbol error")
	}
	if !strings.Contains(err.Error(), "has no symbol to attach to") || !strings.Contains(err.Error(), "model.go:3") {
		t.Fatalf("expected attach error with location, got: %v", err)
	}
}

// Props attach syntactically to types, fields (doc and trailing position), methods, functions,
// interface methods, and embedded fields.
func TestPropsAttachToSymbols(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User

//mgo:api owner=core
type User struct {
	//mgo:validate required max=2000
	Text string

	Rating int //mgo:validate min=1 max=5

	//mgo:flatten
	Base
}

type Base struct{}

//mgo:route member
func (u User) Show() {}

//mgo:job cron=daily
func Cleanup() {}

type Store interface {
	//mgo:scope admin
	Delete(id string) error
}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
{{- $store := index .Package.Types 2 -}}
{{- $cleanup := index .Package.Functions 0 -}}
const Summary = {{ quote (printf "type=%s text_req=%t text_max=%s rating_min=%s rating_max=%s base=%t method=%t fn=%s iface=%t"
	(prop . "api" "owner")
	(propHas (index .Fields 0) "validate" "required")
	(prop (index .Fields 0) "validate" "max")
	(prop (index .Fields 1) "validate" "min")
	(prop (index .Fields 1) "validate" "max")
	(propExists (index .Fields 2) "flatten")
	(propHas (index .Methods 0) "route" "member")
	(prop $cleanup "job" "cron")
	(propHas (index $store.Methods 0) "scope" "admin")) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"type=core text_req=true text_max=2000 rating_min=1 rating_max=5 base=true method=true fn=daily iface=true\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// The flatten group has no key=value args but exists; propExists distinguishes that from absent
// groups, and bare flags are matched by propHas.
func TestPropsFlagsAndExistence(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User

type User struct {
	//mgo:pii
	Email string
}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Summary = {{ quote (printf "pii=%t missing=%t flag=%t missing_key=%q" (propExists (index .Fields 0) "pii") (propExists (index .Fields 0) "nope") (propHas (index .Fields 0) "pii" "pii") (prop (index .Fields 0) "nope" "key")) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"pii=true missing=false flag=false missing_key=\\\"\\\"\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// Multiple //mgo:lines on one symbol: distinct groups stay separate; duplicate groups merge
// with flags unioned and later keys winning.
func TestPropsGroupsMergeAndStack(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User

type User struct {
	//mgo:validate required max=100
	//mgo:validate required max=200 min=1
	//mgo:db column=email_addr
	Email string
}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
{{- $email := index .Fields 0 -}}
const Summary = {{ quote (printf "max=%s min=%s flags=%s column=%s" (prop $email "validate" "max") (prop $email "validate" "min") (join (props $email "validate").Argv ",") (prop $email "db" "column")) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"max=200 min=1 flags=required column=email_addr\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// A props line equidistant between two fields attaches to the one below, matching Go's
// doc-comment convention.
func TestPropsEquidistantPrefersSymbolBelow(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User

type User struct {
	Above string
	//mgo:g here
	Below string
}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Summary = {{ quote (printf "above=%t below=%t" (propHas (index .Fields 0) "g" "here") (propHas (index .Fields 1) "g" "here")) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"above=false below=true\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// Props attach per file: a symbol on a nearby line in another file must not capture them.
func TestPropsAttachWithinOwnFileOnly(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "a.go"), `package fixture

//mgo:g mine
type A string
`)
	writeTestFile(t, filepath.Join(dir, "z.go"), `package fixture

//mgo:gen summary B

type B string
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
{{- $a := index .Package.Types 0 -}}
const Summary = {{ quote (printf "a=%t b=%t" (propHas $a "g" "mine") (propHas .Type "g" "mine")) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"a=true b=false\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// prop helpers are nil-safe on symbols without any props.
func TestPropHelpersNilSafety(t *testing.T) {
	field := Field{Name: "Plain"}
	if propValue(field, "g", "k") != "" {
		t.Fatal("prop on propless field should be empty")
	}
	if propHasFlag(field, "g", "flag") {
		t.Fatal("propHas on propless field should be false")
	}
	if propGroupExists(field, "g") {
		t.Fatal("propExists on propless field should be false")
	}
	if group := propGroup(field, "g"); group.Group != "" || len(group.Args) != 0 || len(group.Argv) != 0 {
		t.Fatalf("props on propless field should be zero, got %#v", group)
	}
	if propsOf(nil) != nil {
		t.Fatal("propsOf(nil) should be nil")
	}
	if propValue("not a symbol", "g", "k") != "" {
		t.Fatal("prop on non-symbol should be empty")
	}
}

// propsOf resolves through invocations to the targeted method, function, or type.
func TestPropsVisibleThroughInvocation(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:api version=2
type User struct{}

//mgo:gen describe User
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "describe" }}
const Version = {{ quote (prop . "api" "version") }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Version = \"2\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// One aggregator annotation can read every annotation in the package via .Package.Metas, in
// deterministic file-then-line order, with args, argv, and location. Props metas attach to
// symbols instead and never appear there. This is the primitive for many-annotations-one-artifact
// generators such as HTTP route tables.
func TestPackageMetasAggregation(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "a.go"), `package fixture

//mgo:gen get /posts/{postID} auth=required
func ShowPost() {}

//mgo:internal flag
type helper struct{}
`)
	writeTestFile(t, filepath.Join(dir, "b.go"), `package fixture

//mgo:gen post /posts
func CreatePost() {}

//mgo:gen server
type Server struct{}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "get" }}{{ end }}
{{ define "post" }}{{ end }}
{{ define "server" }}
const Routes = {{ quote (printf "%s" .Package.Metas) }}
const Table = "
{{- range .Package.Metas }}
{{- if or (eq .Template "get") (eq .Template "post") }}
{{- upper .Template }} {{ index .Argv 0 }} auth={{ index .Args "auth" }};
{{- end }}
{{- end }}"
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	output := string(got)
	if !strings.Contains(output, `const Table = "GET /posts/{postID} auth=required;POST /posts auth=;"`) {
		t.Fatalf("aggregated route table mismatch, got:\n%s", output)
	}
	if strings.Contains(output, "props") || strings.Contains(output, "internal") {
		t.Fatalf("props metas must not appear in .Package.Metas, got:\n%s", output)
	}
}

// The aggregator sees inline annotations too, marked with Inline.
func TestPackageMetasIncludeInlineAnnotations(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

type A string

//mgo:inline stringer A

//mgo:gen summary A
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (a {{ name . }}) String() string { return string(a) }
{{ end }}
{{ define "summary" }}
const Summary = {{ quote (printf "%d" (len .Package.Metas)) }}
{{- range .Package.Metas }}{{ if .Inline }}
const InlineTemplate = {{ quote .Template }}
{{- end }}{{ end }}
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	sidecar := string(files[filepath.Join(dir, "meta.go")])
	if !strings.Contains(sidecar, `const Summary = "2"`) || !strings.Contains(sidecar, `const InlineTemplate = "stringer"`) {
		t.Fatalf("expected inline meta in .Package.Metas, got:\n%s", sidecar)
	}
}

// A directive written in a symbol's doc comment (no blank line) is anchored: the target is the
// symbol below and never needs repeating.
func TestAnchoredGenInfersTarget(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen stringer
type Status string
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (x {{ name . }}) String() string { return string(x) }
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "func (x Status) String() string") {
		t.Fatalf("anchored gen should target the type below, got:\n%s", got)
	}
}

func TestPackageAnchoredGenNeedsNoSymbolTarget(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "doc.go"), `// Package fixture is generated for this test.
//
//mgo:gen packageinfo feature speed=fast
package fixture
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "packageinfo" }}
const PackageInfo = {{ quote (printf "%s|%s|%s|%t|%t|%t|%s|%s" .Package.Name .Kind .Name .IsPackage .IsType .Meta.PackageScoped (index .Argv 0) (index .Args "speed")) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), `const PackageInfo = "fixture|package||true|false|true|feature|fast"`) {
		t.Fatalf("package-anchored invocation mismatch, got:\n%s", got)
	}
}

func TestPackageAnchoredInlineIsRejected(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "doc.go"), `//mgo:inline packageinfo
package fixture
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "packageinfo" }}const Generated = true{{ end }}`)

	_, err := generate(dir)
	if err == nil || !strings.Contains(err.Error(), "package-level directives only support //mgo:gen") {
		t.Fatalf("generate error = %v, want package-level inline diagnostic", err)
	}
}

// In anchored position every bare token after the template name is a positional arg, never a
// target; the standalone form keeps target-first grammar.
func TestAnchoredBareTokensAreArgs(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen describe loud speed=fast
type Status string
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "describe" }}
const Doc = "{{ name . }} {{ index .Argv 0 }} {{ index .Args "speed" }}"
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), `const Doc = "Status loud fast"`) {
		t.Fatalf("anchored bare token should be a positional arg, got:\n%s", got)
	}
}

// Anchored directives work on functions and methods too.
func TestAnchoredFunctionAndMethodTargets(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

type Server struct{}

//mgo:gen describe
func (s *Server) Serve() {}

//mgo:gen describe
func Helper() {}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "describe" }}
const Doc{{ name . }} = "{{ .Kind }}"
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	output := string(got)
	if !strings.Contains(output, `const DocServe = "method"`) || !strings.Contains(output, `const DocHelper = "function"`) {
		t.Fatalf("anchored directives should target method and function, got:\n%s", output)
	}
}

func TestAnchoredConstAndVarTargets(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen describe label=limit
//mgo:api public
const Limit int = 2 + 3

//mgo:gen describe label=greeting
var Greeting = "hello"
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "describe" }}
const Meta{{ .Name }} = {{ quote (printf "%s|%s|%s|%s|%s|value=%t|const=%t|var=%t|label=%s|public=%t" .Kind (typeof .) .Expr .Value.Expr .Value.Value .IsValue .IsConst .IsVar (arg "label") (propHas . "api" "public")) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	output := string(got)
	if !strings.Contains(output, `const MetaLimit = "const|int|2 + 3|2 + 3|2 + 3|value=true|const=true|var=false|label=limit|public=true"`) {
		t.Fatalf("anchored const metadata mismatch, got:\n%s", output)
	}
	if !strings.Contains(output, `const MetaGreeting = "var||\"hello\"|\"hello\"|\"hello\"|value=true|const=false|var=true|label=greeting|public=false"`) {
		t.Fatalf("anchored var metadata mismatch, got:\n%s", output)
	}
}

func TestExplicitTargetsSupportMultiNameConstAndVar(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen describe First
const First, Second = 1, 2

var Empty string

//mgo:gen describe Empty
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "describe" }}
const Meta{{ .Name }} = {{ quote (printf "%s|%s|%s" .Kind (typeof .) .Value.Expr) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	output := string(got)
	if !strings.Contains(output, `const MetaFirst = "const||1"`) {
		t.Fatalf("explicit const target mismatch, got:\n%s", output)
	}
	if !strings.Contains(output, `const MetaEmpty = "var|string|"`) {
		t.Fatalf("explicit var target mismatch, got:\n%s", output)
	}
}

func TestAnchoredInlineValueSpecInsertsAfterDeclarationBlock(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

const (
	//mgo:inline describe
	Limit = 3
)

type After struct{}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "describe" }}
const Meta{{ .Name }} = {{ quote (printf "%s=%s" .Kind .Value.Expr) }}
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	blockEnd := strings.Index(got, ")")
	generated := strings.Index(got, `const MetaLimit = "const=3"`)
	end := strings.Index(got, "//mgo:end")
	after := strings.Index(got, "type After")
	if blockEnd == -1 || generated == -1 || end == -1 || !(blockEnd < generated && generated < end && end < after) {
		t.Fatalf("inline value output must follow the complete declaration block, got:\n%s", got)
	}

	writeTestFile(t, model, got)
	files, err = generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	if regenerated := string(files[model]); regenerated != got {
		t.Fatalf("inline value regeneration should be idempotent\n\n--- first ---\n%s\n--- second ---\n%s", got, regenerated)
	}
}

// An anchored //mgo:inline inserts its output after the annotated symbol and appends //mgo:end on
// the first run; regeneration replaces only the region between the symbol and //mgo:end.
func TestAnchoredInlineInsertsAfterSymbol(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

//mgo:inline signals
type AuthSignals struct {
	Email string
}

type After struct{}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "signals" }}
const Sig{{ name . }} = "{{ name . }}"
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	typeEnd := strings.Index(got, "}")
	genPos := strings.Index(got, "const SigAuthSignals")
	endPos := strings.Index(got, "//mgo:end")
	afterPos := strings.Index(got, "type After")
	if genPos == -1 || endPos == -1 {
		t.Fatalf("expected generated const and //mgo:end, got:\n%s", got)
	}
	if !(typeEnd < genPos && genPos < endPos && endPos < afterPos) {
		t.Fatalf("generated block must sit between the type and the next symbol, got:\n%s", got)
	}

	// Regeneration must be idempotent: the block is replaced in place, never duplicated.
	writeTestFile(t, model, got)
	files, err = generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	regen := string(files[model])
	if regen != got {
		t.Fatalf("regeneration should be idempotent\n\n--- first ---\n%s\n--- second ---\n%s", got, regen)
	}
	if strings.Count(regen, "const SigAuthSignals") != 1 {
		t.Fatalf("generated const should appear exactly once, got:\n%s", regen)
	}
}

// Stale content between an anchored symbol and its //mgo:end is replaced, and the symbol itself is
// never touched.
func TestAnchoredInlineReplacesStaleBlock(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

//mgo:inline signals
type AuthSignals struct {
	Email string
}

const SigOld = "stale"

//mgo:end
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "signals" }}
const SigNew = "fresh"
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	if strings.Contains(got, "SigOld") {
		t.Fatalf("stale block should be replaced, got:\n%s", got)
	}
	if !strings.Contains(got, "type AuthSignals struct") || !strings.Contains(got, "Email string") {
		t.Fatalf("annotated type must survive regeneration, got:\n%s", got)
	}
	if strings.Count(got, `const SigNew = "fresh"`) != 1 {
		t.Fatalf("generated block should appear exactly once, got:\n%s", got)
	}
}

// Stacked anchored inline directives compose: outputs land one after another in directive order,
// sharing a single region and a single //mgo:end.
func TestAnchoredInlineStackComposes(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

//mgo:inline first
//mgo:inline second
type Thing struct{}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "first" }}
const First{{ name . }} = 1
{{ end }}
{{ define "second" }}
const Second{{ name . }} = 2
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	firstPos := strings.Index(got, "const FirstThing")
	secondPos := strings.Index(got, "const SecondThing")
	if firstPos == -1 || secondPos == -1 || firstPos > secondPos {
		t.Fatalf("stacked inline outputs must appear in directive order, got:\n%s", got)
	}
	if strings.Count(got, "//mgo:end") != 1 {
		t.Fatalf("a stacked inline region shares one //mgo:end, got:\n%s", got)
	}

	writeTestFile(t, model, got)
	files, err = generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	if regen := string(files[model]); regen != got {
		t.Fatalf("stacked regeneration should be idempotent\n\n--- first ---\n%s\n--- second ---\n%s", got, regen)
	}
}

// gen and inline can stack on the same symbol: gen output goes to the sidecar, inline output after
// the symbol.
func TestAnchoredStackMixesGenAndInline(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

//mgo:gen sidecar
//mgo:inline local
type Thing struct{}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "sidecar" }}
const InSidecar{{ name . }} = true
{{ end }}
{{ define "local" }}
const Inline{{ name . }} = true
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	inline := string(files[model])
	sidecar := string(files[filepath.Join(dir, "meta.go")])
	if !strings.Contains(inline, "const InlineThing = true") || strings.Contains(inline, "InSidecar") {
		t.Fatalf("inline file should hold only the inline block, got:\n%s", inline)
	}
	if !strings.Contains(sidecar, "const InSidecarThing = true") || strings.Contains(sidecar, "InlineThing") {
		t.Fatalf("sidecar should hold only the gen block, got:\n%s", sidecar)
	}
}

// Within a directive stack //mgo:must come after gen/inline directives; props attach to the
// symbol below as usual.
func TestPropsOrderingInStack(t *testing.T) {
	template := `{{ define "describe" }}
const Doc = "{{ name . }} {{ prop . "api" "version" }}"
{{ end }}
`
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen describe
//mgo:api version=v2
type Status string
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), template)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), `const Doc = "Status v2"`) {
		t.Fatalf("props after gen in a stack should attach to the symbol, got:\n%s", got)
	}

	dir = t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:api version=v2
//mgo:gen describe
type Status string
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), template)

	_, err = generate(dir)
	if err == nil {
		t.Fatal("expected props-before-gen ordering error")
	}
	if !strings.Contains(err.Error(), "//mgo:gen must come before properties") || !strings.Contains(err.Error(), "model.go:4") {
		t.Fatalf("expected ordering error with location, got: %v", err)
	}
}

// Field props inside an anchored struct never hijack the inline end-binding.
func TestAnchoredInlineSkipsFieldPropsForEndBinding(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

//mgo:inline signals
type AuthSignals struct {
	Email string //mgo:validate required
}

const SigOld = "stale"

//mgo:end
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "signals" }}
const SigNew = "fresh"
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	if strings.Contains(got, "SigOld") || strings.Count(got, "//mgo:end") != 1 {
		t.Fatalf("end binding must skip field props and reuse the existing //mgo:end, got:\n%s", got)
	}
}

// A blank line between directive and symbol keeps standalone semantics: first bare token is still
// a target.
func TestBlankLineKeepsStandaloneSemantics(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen stringer Code

type Status string

type Code string
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (x {{ name . }}) String() string { return string(x) }
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "func (x Code) String() string") {
		t.Fatalf("standalone directive must honor its explicit target, got:\n%s", got)
	}
}

func TestReservedFutureDirectivesError(t *testing.T) {
	for _, directive := range []string{"build", "config", "file", "format", "generate", "import", "include", "option", "options", "output", "package", "plugin", "profile", "use"} {
		t.Run(directive, func(t *testing.T) {
			dir := t.TempDir()
			writeTestFile(t, filepath.Join(dir, "model.go"), "package fixture\n\n//mgo:"+directive+" value\n")
			_, err := generate(dir)
			if err == nil || !strings.Contains(err.Error(), `directive "`+directive+`" is reserved for future metago features`) {
				t.Fatalf("unexpected error: %v", err)
			}
		})
	}
}

func TestReservedGenerationArgumentsError(t *testing.T) {
	keys := []string{"build", "dir", "file", "format", "group", "mode", "order", "output", "package", "scope", "tags", "mgo", "mgo.file", "mgo_output", "mgo-option"}
	for _, directive := range []string{"gen", "inline"} {
		for _, key := range keys {
			t.Run(directive+"/"+key, func(t *testing.T) {
				dir := t.TempDir()
				writeTestFile(t, filepath.Join(dir, "model.go"), "package fixture\n\n//mgo:"+directive+" custom "+key+"=value\ntype User struct{}\n")
				writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "custom" }}x{{ end }}`)
				_, err := generate(dir)
				if err == nil || !strings.Contains(err.Error(), `argument "`+key+`" is reserved for future metago features`) {
					t.Fatalf("unexpected error: %v", err)
				}
			})
		}
	}
}

func TestPropertyArgumentsAreNotReserved(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:database file=schema.sql format=postgres mgo.profile=test
type User struct{}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}x{{ end }}`)
	if _, err := generate(dir); err != nil {
		t.Fatalf("property arguments should remain unrestricted: %v", err)
	}
}

func TestPropertyMustBeSyntacticallyAttached(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:banana yellow=true

func Unrelated() {}
`)
	_, err := generate(dir)
	if err == nil || !strings.Contains(err.Error(), `property "banana" has no symbol to attach to`) {
		t.Fatalf("unexpected error: %v", err)
	}
}
