package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"sort"
	"text/template"
)

func generate(dir string) ([]byte, error) {
	files, err := generateFiles(dir)
	if err != nil {
		return nil, err
	}
	outputs := sortedMapKeys(files)
	if len(outputs) == 0 {
		return nil, nil
	}
	return files[outputs[0]], nil
}

func generateFiles(dir string) (map[string][]byte, error) {
	templateFiles, err := findTemplateFiles(dir)
	if err != nil {
		return nil, err
	}
	resolver, _, err := newResolver(dir)
	if err != nil {
		return nil, err
	}
	return generateFilesWithTemplates(dir, templateFiles, resolver)
}

var diagnosticWriter io.Writer = os.Stderr

type templateFailure struct{ message string }

func (e templateFailure) Error() string { return e.message }

func generateFilesWithTemplates(dir string, templateFiles []string, resolver *targetResolver) (map[string][]byte, error) {
	pkg, metas, err := scanPackage(dir)
	if err != nil {
		return nil, err
	}
	logger.Debug("scanned package", "package", pkg.Name, "types", len(pkg.Types), "metas", len(metas))

	files := map[string][]byte{}
	var diagnostics []error
	generatePackageFiles(files, templateFiles, resolver, pkg, metas, metaOutputPath(dir), &diagnostics)

	testPackages, err := scanTestPackages(dir, pkg.Name)
	if err != nil {
		return nil, err
	}
	for _, testPkg := range testPackages {
		output := testMetaOutputPath(dir, pkg.Name, testPkg.Name)
		generatePackageFiles(files, templateFiles, resolver, testPkg, testPkg.Metas, output, &diagnostics)
	}
	if len(diagnostics) > 0 {
		return nil, errors.Join(diagnostics...)
	}
	return files, nil
}

func generatePackageFiles(files map[string][]byte, templateFiles []string, resolver *targetResolver, pkg *Package, metas []Meta, output string, diagnostics *[]error) {
	generatedGroups := map[string][]Meta{}
	inlineGroups := map[string][]Meta{}
	for _, meta := range metas {
		if meta.Inline {
			inlineGroups[meta.File] = append(inlineGroups[meta.File], meta)
		} else {
			generatedGroups[output] = append(generatedGroups[output], meta)
		}
	}
	for _, path := range sortedMapKeys(generatedGroups) {
		src, err := generateMetas(templateFiles, pkg, generatedGroups[path], resolver)
		if err != nil {
			*diagnostics = append(*diagnostics, err)
			continue
		}
		files[path] = src
	}
	for _, file := range sortedMapKeys(inlineGroups) {
		src, err := generateInlineFile(templateFiles, pkg, file, inlineGroups[file], resolver)
		if err != nil {
			*diagnostics = append(*diagnostics, err)
			continue
		}
		files[file] = src
	}
}

func generateMetas(templateFiles []string, pkg *Package, metas []Meta, resolver *targetResolver) ([]byte, error) {
	imports := newImportSet()
	body, err := executeMetas(templateFiles, pkg, metas, imports, resolver)
	if err != nil {
		return nil, err
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by metago; DO NOT EDIT.\n\npackage %s\n\n", pkg.Name)
	imports.write(&out)
	out.Write(body)

	src := out.Bytes()
	logger.Debug("formatting generated source", "bytes", len(src))
	formatted, err := format.Source(src)
	if err == nil {
		src = formatted
		logger.Debug("formatted generated source", "bytes", len(src))
	} else {
		logger.Warn("generated source could not be formatted; writing raw output", "error", err)
	}
	return src, nil
}

func executeMetas(templateFiles []string, pkg *Package, metas []Meta, imports *importSet, resolver *targetResolver) ([]byte, error) {
	var body bytes.Buffer
	var diagnostics []error

	for _, meta := range metas {
		data, err := resolver.resolveInvocation(pkg, meta)
		if err != nil {
			diagnostics = append(diagnostics, err)
			continue
		}

		logger.Debug("executing template", "template", meta.Template, "target", data.Name, "file", meta.File, "line", meta.Line, "inline", meta.Inline, "kind", data.Kind)
		invocationImports := newImportSet()
		helpers := template.FuncMap{
			"warn": func(message string) string {
				fmt.Fprintf(diagnosticWriter, "%s:%d: warning: template %q: %s\n", meta.File, meta.Line, meta.Template, message)
				return ""
			},
			"fail": func(message string) (string, error) {
				return "", templateFailure{message: message}
			},
		}
		tmpl, err := loadTemplates(templateFiles, invocationImports.add, func(key any) string {
			return argValue(meta, key)
		}, helpers)
		if err != nil {
			return nil, err
		}
		var invocationBody bytes.Buffer
		if err := tmpl.ExecuteTemplate(&invocationBody, meta.Template, data); err != nil {
			var failure templateFailure
			if errors.As(err, &failure) {
				diagnostics = append(diagnostics, fmt.Errorf("%s:%d: error: template %q: %s", meta.File, meta.Line, meta.Template, failure.message))
			} else {
				diagnostics = append(diagnostics, fmt.Errorf("%s:%d: execute template %q: %w", meta.File, meta.Line, meta.Template, err))
			}
			continue
		}
		imports.merge(invocationImports)
		body.Write(invocationBody.Bytes())
		body.WriteByte('\n')
	}
	return body.Bytes(), errors.Join(diagnostics...)
}
func metaOutputPath(dir string) string {
	return filepath.Join(dir, "meta.go")
}

func testMetaOutputPath(dir, basePackage, testPackage string) string {
	if testPackage == basePackage {
		return filepath.Join(dir, "meta_test.go")
	}
	return filepath.Join(dir, "meta_"+basePackage+"_test.go")
}

func sortedMapKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
