package main

import (
	"bytes"
	"fmt"
	"go/format"
	"path/filepath"
	"sort"
)

func generate(dir string) ([]byte, error) {
	files, err := generateFiles(dir)
	if err != nil {
		return nil, err
	}
	outputs := sortedMapKeys(files)
	if len(outputs) == 0 {
		return nil, nil
	}
	return files[outputs[0]], nil
}

func generateFiles(dir string) (map[string][]byte, error) {
	templateFiles, err := findTemplateFiles(dir)
	if err != nil {
		return nil, err
	}
	resolver, _, err := newResolver(dir)
	if err != nil {
		return nil, err
	}
	return generateFilesWithTemplates(dir, templateFiles, resolver)
}

func generateFilesWithTemplates(dir string, templateFiles []string, resolver *targetResolver) (map[string][]byte, error) {
	pkg, metas, err := scanPackage(dir)
	if err != nil {
		return nil, err
	}
	logger.Debug("scanned package", "package", pkg.Name, "types", len(pkg.Types), "metas", len(metas))
	if len(metas) == 0 {
		return nil, nil
	}

	generatedGroups := map[string][]Meta{}
	inlineGroups := map[string][]Meta{}
	for _, meta := range metas {
		if meta.Inline {
			inlineGroups[meta.File] = append(inlineGroups[meta.File], meta)
			continue
		}
		output := metaOutputPath(dir)
		generatedGroups[output] = append(generatedGroups[output], meta)
	}

	files := map[string][]byte{}
	outputs := sortedMapKeys(generatedGroups)
	for _, output := range outputs {
		src, err := generateMetas(templateFiles, pkg, generatedGroups[output], resolver)
		if err != nil {
			return nil, err
		}
		files[output] = src
	}

	inlineFiles := sortedMapKeys(inlineGroups)
	for _, file := range inlineFiles {
		src, err := generateInlineFile(templateFiles, pkg, file, inlineGroups[file], resolver)
		if err != nil {
			return nil, err
		}
		files[file] = src
	}
	return files, nil
}

func generateMetas(templateFiles []string, pkg *Package, metas []Meta, resolver *targetResolver) ([]byte, error) {
	imports := newImportSet()
	body, err := executeMetas(templateFiles, pkg, metas, imports, resolver)
	if err != nil {
		return nil, err
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by metago; DO NOT EDIT.\n\npackage %s\n\n", pkg.Name)
	imports.write(&out)
	out.Write(body)

	src := out.Bytes()
	logger.Debug("formatting generated source", "bytes", len(src))
	formatted, err := format.Source(src)
	if err == nil {
		src = formatted
		logger.Debug("formatted generated source", "bytes", len(src))
	} else {
		logger.Warn("generated source could not be formatted; writing raw output", "error", err)
	}
	return src, nil
}

func executeMetas(templateFiles []string, pkg *Package, metas []Meta, imports *importSet, resolver *targetResolver) ([]byte, error) {
	var body bytes.Buffer

	for _, meta := range metas {
		data, err := resolver.resolveInvocation(pkg, meta)
		if err != nil {
			return nil, err
		}

		logger.Debug("executing template", "template", meta.Template, "target", data.Name, "file", meta.File, "line", meta.Line, "inline", meta.Inline, "kind", data.Kind)
		tmpl, err := loadTemplates(templateFiles, imports.add, func(key any) string {
			return argValue(meta, key)
		})
		if err != nil {
			return nil, err
		}
		if err := tmpl.ExecuteTemplate(&body, meta.Template, data); err != nil {
			return nil, fmt.Errorf("%s:%d: execute template %q: %w", meta.File, meta.Line, meta.Template, err)
		}
		body.WriteByte('\n')
	}
	return body.Bytes(), nil
}
func metaOutputPath(dir string) string {
	return filepath.Join(dir, "meta.go")
}

func sortedMapKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
