package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"path/filepath"
	"sort"
	"text/template"
)

func generate(dir string) ([]byte, error) {
	files, err := generateFiles(dir)
	if err != nil {
		return nil, err
	}
	outputs := sortedMapKeys(files)
	if len(outputs) == 0 {
		return nil, nil
	}
	return files[outputs[0]], nil
}

func generateFiles(dir string) (map[string][]byte, error) {
	templateFiles, err := findTemplateFiles(dir)
	if err != nil {
		return nil, err
	}
	resolver, _, err := newResolver(dir)
	if err != nil {
		return nil, err
	}
	return generateFilesWithTemplates(dir, templateFiles, resolver)
}

const generatedHeader = "// Code generated by metago; DO NOT EDIT.\n"

type templateFailure struct{ message string }

func (e templateFailure) Error() string { return e.message }

func generateFilesWithTemplates(dir string, templateFiles []string, resolver *targetResolver) (map[string][]byte, error) {
	pkg, metas, err := scanPackage(dir)
	if err != nil {
		return nil, err
	}
	logger.Debug("scanned package", "package", pkg.Name, "types", len(pkg.Types), "metas", len(metas))

	files := map[string][]byte{}
	var diagnostics []error
	generatePackageFiles(files, templateFiles, resolver, pkg, metas, metaOutputPath(dir), &diagnostics)

	testPackages, err := scanTestPackages(dir, pkg.Name)
	if err != nil {
		return nil, err
	}
	for _, testPkg := range testPackages {
		output := testMetaOutputPath(dir, pkg.Name, testPkg.Name)
		generatePackageFiles(files, templateFiles, resolver, testPkg, testPkg.Metas, output, &diagnostics)
	}
	if len(diagnostics) > 0 {
		return nil, errors.Join(diagnostics...)
	}
	return files, nil
}

func generatePackageFiles(files map[string][]byte, templateFiles []string, resolver *targetResolver, pkg *Package, metas []Meta, output string, diagnostics *[]error) {
	generatedGroups := map[string][]Meta{}
	sourceGroups := map[string][]Meta{}
	for _, meta := range metas {
		if meta.Inline || meta.EndLine > 0 {
			sourceGroups[meta.File] = append(sourceGroups[meta.File], meta)
		}
		if !meta.Inline {
			generatedGroups[output] = append(generatedGroups[output], meta)
		}
	}
	for _, path := range sortedMapKeys(generatedGroups) {
		src, err := generateMetas(templateFiles, pkg, generatedGroups[path], resolver)
		if err != nil {
			*diagnostics = append(*diagnostics, err)
			continue
		}
		files[path] = src
	}
	for _, file := range sortedMapKeys(sourceGroups) {
		src, err := generateInlineFile(templateFiles, pkg, file, sourceGroups[file], resolver)
		if err != nil {
			*diagnostics = append(*diagnostics, err)
			continue
		}
		files[file] = src
	}
}

func generateMetas(templateFiles []string, pkg *Package, metas []Meta, resolver *targetResolver) ([]byte, error) {
	imports := newImportSet()
	body, err := executeMetas(templateFiles, pkg, metas, imports, resolver)
	if err != nil {
		return nil, err
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "%s\npackage %s\n\n", generatedHeader, pkg.Name)
	imports.write(&out)
	out.Write(body)

	src := out.Bytes()
	logger.Debug("formatting generated source", "bytes", len(src))
	formatted, err := format.Source(src)
	if err == nil {
		src = formatted
		logger.Debug("formatted generated source", "bytes", len(src))
	} else {
		logger.Warn("generated source could not be formatted; writing raw output", "error", err)
	}
	return src, nil
}

func executeMetas(templateFiles []string, pkg *Package, metas []Meta, imports *importSet, resolver *targetResolver) ([]byte, error) {
	var body bytes.Buffer
	var diagnostics []error
	emitted := map[string]struct{}{}

	for _, meta := range metas {
		data, err := resolver.resolveInvocation(pkg, meta)
		if err != nil {
			diagnostics = append(diagnostics, err)
			continue
		}

		logger.Debug("executing template", "template", meta.Template, "target", data.Name, "file", meta.File, "line", meta.Line, "inline", meta.Inline, "kind", data.Kind)
		invocationImports := newImportSet()
		pendingEmissions := map[string]struct{}{}
		helpers := template.FuncMap{
			"fail": func(message string) (string, error) {
				return "", templateFailure{message: message}
			},
			"emitOnce": func(key string) (bool, error) {
				if key == "" {
					return false, errors.New("emitOnce key cannot be empty")
				}
				if _, ok := emitted[key]; ok {
					return false, nil
				}
				if _, ok := pendingEmissions[key]; ok {
					return false, nil
				}
				pendingEmissions[key] = struct{}{}
				return true, nil
			},
		}
		tmpl, err := loadTemplates(templateFiles, invocationImports.add, func(key any) string {
			return argValue(data.Meta, key)
		}, helpers)
		if err != nil {
			return nil, err
		}
		var invocationBody bytes.Buffer
		if err := tmpl.ExecuteTemplate(&invocationBody, meta.Template, data); err != nil {
			if failure, ok := errors.AsType[templateFailure](err); ok {
				diagnostics = append(diagnostics, fmt.Errorf("%s:%d: error: template %q: %s", meta.File, meta.Line, meta.Template, failure.message))
			} else {
				diagnostics = append(diagnostics, fmt.Errorf("%s:%d: execute template %q: %w", meta.File, meta.Line, meta.Template, err))
			}
			continue
		}
		imports.merge(invocationImports)
		for key := range pendingEmissions {
			emitted[key] = struct{}{}
		}
		body.Write(invocationBody.Bytes())
		body.WriteByte('\n')
	}
	return body.Bytes(), errors.Join(diagnostics...)
}
func metaOutputPath(dir string) string {
	return filepath.Join(dir, "meta.go")
}

func testMetaOutputPath(dir, basePackage, testPackage string) string {
	if testPackage == basePackage {
		return filepath.Join(dir, "meta_test.go")
	}
	return filepath.Join(dir, "meta_"+basePackage+"_test.go")
}

func sortedMapKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
