package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGoldenFixtures(t *testing.T) {
	cases, err := filepath.Glob(filepath.Join("testdata", "*"))
	if err != nil {
		t.Fatal(err)
	}
	if len(cases) == 0 {
		t.Fatal("no golden fixtures found")
	}

	for _, dir := range cases {
		t.Run(filepath.Base(dir), func(t *testing.T) {
			got, err := generate(dir)
			if err != nil {
				t.Fatal(err)
			}

			golden := filepath.Join(dir, "metago_meta.go.golden")
			if os.Getenv("UPDATE_GOLDEN") == "1" {
				if err := os.WriteFile(golden, got, 0644); err != nil {
					t.Fatal(err)
				}
				return
			}

			want, err := os.ReadFile(golden)
			if err != nil {
				t.Fatal(err)
			}
			if string(got) != string(want) {
				t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
			}
		})
	}
}

func TestMetaCommentsRequireNoSpace(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), "package fixture\n\n// #stringer Status\ntype Status string\n")
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (x {{ name . }}) String() string { return string(x) }
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 0 {
		t.Fatalf("space-separated meta comment should be ignored, got:\n%s", got)
	}
}

func TestRunRecursesIntoSubpackages(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "embed.go"), "package app\n")

	views := filepath.Join(root, "views")
	if err := os.Mkdir(views, 0755); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, filepath.Join(views, "page_index.go"), "package views\n\n//#signals AgentSignals\ntype AgentSignals struct {\n\tName string `json:\"name\"`\n}\n")
	templates := filepath.Join(root, "metago")
	if err := os.Mkdir(templates, 0755); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, filepath.Join(templates, "fields.metago"), `{{ define "signals" }}
const (
{{- range .Fields }}
	{{ name . }} = {{ quote (tag . "json") }}
{{- end }}
)
{{ end }}
`)

	if err := run(root); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(views, "page_index_meta.go"))
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage views\n\nconst (\n\tName = \"name\"\n)\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestInlineMetaUpdatesSourceFile(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

type A string

//@stringer A
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (a {{ name . }}) String() string { return string(a) }
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	want := `package fixture

type A string

//@stringer A

func (a A) String() string { return string(a) }

//end
`
	if got != want {
		t.Fatalf("inline output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
	if _, ok := files[filepath.Join(dir, "model_meta.go")]; ok {
		t.Fatal("inline meta should not create a generated sidecar file")
	}
}

func TestUtilityHelpers(t *testing.T) {
	field := Field{Name: "UserID", Type: "[]*User", Tag: `json:"user_id,omitempty"`}
	if got := snakeCase(field); got != "user_id" {
		t.Fatalf("snakeCase = %q", got)
	}
	if got := snakeCase("HTTPServer"); got != "http_server" {
		t.Fatalf("snakeCase acronym = %q", got)
	}
	if got := tagName(field, "json"); got != "user_id" {
		t.Fatalf("tagName = %q", got)
	}
	if !tagExists(field, "json") || !tagHas(field, "json", "omitempty") {
		t.Fatal("tag helpers failed")
	}
	if got := elemType(field); got != "*User" {
		t.Fatalf("elemType = %q", got)
	}
	if got := defaultValue("fallback", ""); got != "fallback" {
		t.Fatalf("defaultValue = %v", got)
	}
}

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(strings.TrimLeft(content, "\n")), 0644); err != nil {
		t.Fatal(err)
	}
}
