package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestGoldenFixtures(t *testing.T) {
	goldens, err := filepath.Glob(filepath.Join("testdata", "*", "meta.go.golden"))
	if err != nil {
		t.Fatal(err)
	}
	if len(goldens) == 0 {
		t.Fatal("no golden fixtures found")
	}

	for _, golden := range goldens {
		dir := filepath.Dir(golden)
		t.Run(filepath.Base(dir), func(t *testing.T) {
			got, err := generate(dir)
			if err != nil {
				t.Fatal(err)
			}

			if os.Getenv("UPDATE_GOLDEN") == "1" {
				if err := os.WriteFile(golden, got, 0644); err != nil {
					t.Fatal(err)
				}
				return
			}

			want, err := os.ReadFile(golden)
			if err != nil {
				t.Fatal(err)
			}
			if string(got) != string(want) {
				t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
			}
		})
	}
}

// Comments that are not exact //mgo: directives are prose: a space anywhere breaks the directive
// shape, matching gofmt's rule.
func TestNonDirectiveCommentsAreIgnored(t *testing.T) {
	cases := map[string]string{
		"space after //":    "package fixture\n\n// mgo:gen stringer Status\ntype Status string\n",
		"space after colon": "package fixture\n\n// mgo: #stringer Status\ntype Status string\n",
	}
	for name, model := range cases {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			writeTestFile(t, filepath.Join(dir, "model.go"), model)
			writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (x {{ name . }}) String() string { return string(x) }
{{ end }}
`)

			got, err := generate(dir)
			if err != nil {
				t.Fatal(err)
			}
			if len(got) != 0 {
				t.Fatalf("non-directive comment should be ignored, got:\n%s", got)
			}
		})
	}
}

func TestRunRecursesIntoSubpackages(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "embed.go"), "package app\n")

	views := filepath.Join(root, "views")
	if err := os.Mkdir(views, 0755); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, filepath.Join(views, "page_index.go"), "package views\n\n//mgo:gen signals AgentSignals\ntype AgentSignals struct {\n\tName string `json:\"name\"`\n}\n")
	templates := filepath.Join(root, "metago")
	if err := os.Mkdir(templates, 0755); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, filepath.Join(templates, "fields.metago"), `{{ define "signals" }}
const (
{{- range .Fields }}
	{{ name . }} = {{ quote (tag . "json") }}
{{- end }}
)
{{ end }}
`)

	if err := run(root); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(views, "meta.go"))
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage views\n\nconst (\n\tName = \"name\"\n)\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestZeroUsesFieldAndTargetTypes(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User
type User struct {
	ID int
	Name string
	Owner *User
}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Summary = {{ quote (printf "target=%s id=%s name=%s owner=%s" (zero .) (zero (index .Fields 0)) (zero (index .Fields 1)) (zero (index .Fields 2))) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"target=User{} id=0 name=\\\"\\\" owner=nil\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestPositionalMetaArgs(t *testing.T) {
	meta, err := parseMeta("summary User users public mode=fast", "model.go", 3, false)
	if err != nil {
		t.Fatal(err)
	}
	if meta.Target != "User" || len(meta.Argv) != 2 || meta.Argv[0] != "users" || meta.Argv[1] != "public" || meta.Args["mode"] != "fast" {
		t.Fatalf("parseMeta args = %#v", meta)
	}

	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User users public mode=fast

type User struct{}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Summary = {{ quote (printf "first=%s second=%s mode=%s missing=%s" (arg 0) (arg 1) (arg "mode") (arg 2)) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"first=users second=public mode=fast missing=\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestFieldTypeHelpersResolveNamedTypes(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User

type UserID string
type UserIDs []UserID
type UserMap map[string]UserID

type User struct {
	IDs UserIDs
	Lookup UserMap
}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Summary = {{ quote (printf "ids_type=%s ids_slice=%t ids_elem=%s ids_zero=%s lookup_map=%t" (typeof (index .Fields 0)) (isSlice (index .Fields 0)) (elem (index .Fields 0)) (zero (index .Fields 0)) (isMap (index .Fields 1))) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"ids_type=UserIDs ids_slice=true ids_elem=UserID ids_zero=nil lookup_map=true\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestInlineMetaUpdatesSourceFile(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

type A string

//mgo:inline stringer A
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
func (a {{ name . }}) String() string { return string(a) }
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	want := `package fixture

type A string

//mgo:inline stringer A

func (a A) String() string { return string(a) }

//mgo:end
`
	if got != want {
		t.Fatalf("inline output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
	if _, ok := files[filepath.Join(dir, "meta.go")]; ok {
		t.Fatal("inline meta should not create a generated sidecar file")
	}
}

func TestMethodMetadataIncludesSignature(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User

type User struct{}

func (u User) Save(ctx string, retries int) (bool, error) { return false, nil }
func (u *User) Rename(names ...string) error { return nil }
func Standalone() {}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Summary = {{ quote (printf "%s recv=%s/%s p0=%s:%s p1=%s:%s r0=%s r1=%s m1=%s variadic=%t" (index .Methods 0).Name (index .Methods 0).Receiver (index .Methods 0).ReceiverType (index (index .Methods 0).Params 0).Name (index (index .Methods 0).Params 0).Type (index (index .Methods 0).Params 1).Name (index (index .Methods 0).Params 1).Type (index (index .Methods 0).Results 0).Type (index (index .Methods 0).Results 1).Type (index .Methods 1).Name (index (index .Methods 1).Params 0).Variadic) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"Save recv=u/User p0=ctx:string p1=retries:int r0=bool r1=error m1=Rename variadic=true\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestMethodAndFunctionBodies(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary User

type User struct{}

func (u User) Save() error {
	return nil
}

func Helper(name string) string { return name }
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Summary = {{ quote (printf "method=%q function=%s:%q" (index .Methods 0).Body (index .Functions 0).Name (index .Functions 0).Body) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"method=\\\"\\\\n\\\\treturn nil\\\\n\\\" function=Helper:\\\" return name \\\"\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestInterfaceMethodMetadataIncludesSignature(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen summary Store

type Store interface {
	Get(id string) (User, error)
	List(limit int, tags ...string) []User
}

type User struct{}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Summary = {{ quote (printf "%s %s p0=%s:%s r0=%s m1=%s variadic=%t" .Kind (index .Methods 0).Name (index (index .Methods 0).Params 0).Name (index (index .Methods 0).Params 0).Type (index (index .Methods 0).Results 0).Type (index .Methods 1).Name (index (index .Methods 1).Params 1).Variadic) }}
{{ end }}
`)

	got, err := generate(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst Summary = \"interface Get p0=id:string r0=User m1=List variadic=true\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestSidecarMetasSharePackageMetaFile(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "a.go"), `package fixture

//mgo:gen summary A

type A string
`)
	writeTestFile(t, filepath.Join(dir, "b.go"), `package fixture

//mgo:gen summary B

type B string
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const {{ name . }}Name = {{ quote (name .) }}
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := files[filepath.Join(dir, "a_meta.go")]; ok {
		t.Fatal("sidecar meta should not create per-source a_meta.go")
	}
	if _, ok := files[filepath.Join(dir, "b_meta.go")]; ok {
		t.Fatal("sidecar meta should not create per-source b_meta.go")
	}
	got := string(files[filepath.Join(dir, "meta.go")])
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage fixture\n\nconst AName = \"A\"\n\nconst BName = \"B\"\n"
	if got != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestTestMetasUseSeparatePackageSidecars(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package store

type Repository interface { Get() string }
`)
	writeTestFile(t, filepath.Join(dir, "internal_test.go"), `package store

//mgo:gen summary InternalFixture
type InternalFixture struct{}
`)
	writeTestFile(t, filepath.Join(dir, "external_test.go"), `package store_test

//mgo:gen summary ExternalFixture
type ExternalFixture struct{}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "summary" }}
const Generated{{ name . }} = true
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	internal := string(files[filepath.Join(dir, "meta_test.go")])
	if !strings.Contains(internal, "package store") || !strings.Contains(internal, "GeneratedInternalFixture") {
		t.Fatalf("unexpected internal test sidecar:\n%s", internal)
	}
	external := string(files[filepath.Join(dir, "meta_store_test.go")])
	if !strings.Contains(external, "package store_test") || !strings.Contains(external, "GeneratedExternalFixture") {
		t.Fatalf("unexpected external test sidecar:\n%s", external)
	}
	if _, ok := files[filepath.Join(dir, "meta.go")]; ok {
		t.Fatal("test directives must not generate production meta.go")
	}

	// Exercise the complete write path twice: generated sidecars must be ignored on the second scan.
	if err := run(dir); err != nil {
		t.Fatal(err)
	}
	if err := run(dir); err != nil {
		t.Fatalf("regeneration scanned its own output: %v", err)
	}
	writeTestFile(t, filepath.Join(dir, "go.mod"), "module example.com/store\n\ngo 1.23\n")
	cmd := exec.Command("go", "test", "./...")
	cmd.Dir = dir
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated internal and external test packages do not compile: %v\n%s", err, output)
	}
}

func TestStringerRejectsNonPrimitiveTarget(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen stringer
type User struct { Name string }
`)
	templateFile, err := filepath.Abs(filepath.Join("std", "stringer", "stringer.metago"))
	if err != nil {
		t.Fatal(err)
	}
	resolver, _, err := newResolver(dir)
	if err != nil {
		t.Fatal(err)
	}
	files, err := generateFilesWithTemplates(dir, []string{templateFile}, resolver)
	if err == nil {
		t.Fatal("expected stringer to reject a struct target")
	}
	if files != nil {
		t.Fatalf("failed stringer generation returned files: %v", files)
	}
	if !strings.Contains(err.Error(), `template "stringer": stringer requires a primitive-backed type`) {
		t.Fatalf("unexpected stringer diagnostic: %v", err)
	}
}

func TestTemplateDiagnosticsContinueAndDiscardFailedInvocation(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

type BadOne struct{}
type Good struct{}
type BadTwo struct{}

//mgo:gen check BadOne
//mgo:gen good Good
//mgo:gen check BadTwo
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "check" }}
const Partial{{ name . }} = true
{{ imports "strconv" }}
{{ fail (printf "%s is unsupported" (name .)) }}
{{ end }}
{{ define "good" }}
const Complete = true
{{ end }}
`)

	pkg, metas, err := scanPackage(dir)
	if err != nil {
		t.Fatal(err)
	}
	resolver, _, err := newResolver(dir)
	if err != nil {
		t.Fatal(err)
	}
	imports := newImportSet()

	body, err := executeMetas([]string{filepath.Join(dir, "templates.metago")}, pkg, metas, imports, resolver)
	if err == nil {
		t.Fatal("expected failed template diagnostics")
	}
	message := err.Error()
	for _, want := range []string{`template "check": BadOne is unsupported`, `template "check": BadTwo is unsupported`} {
		if !strings.Contains(message, want) {
			t.Errorf("missing diagnostic %q in:\n%s", want, message)
		}
	}
	if strings.Contains(string(body), "Partial") {
		t.Fatalf("failed invocation output was committed:\n%s", body)
	}
	if !strings.Contains(string(body), "const Complete = true") {
		t.Fatalf("successful invocation after a failure was not committed:\n%s", body)
	}
	if len(imports.paths) != 0 {
		t.Fatalf("failed invocation imports were committed: %#v", imports.paths)
	}

	if files, err := generateFiles(dir); err == nil || files != nil {
		t.Fatalf("generation with failures must be atomic; files=%v err=%v", files, err)
	}
}

func TestInlineMetaAddsImports(t *testing.T) {
	dir := t.TempDir()
	model := filepath.Join(dir, "model.go")
	writeTestFile(t, model, `package fixture

type A int

//mgo:inline stringer A
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "stringer" }}
{{ imports "strconv" }}
func (a {{ name . }}) String() string { return strconv.Itoa(int(a)) }
{{ end }}
`)

	files, err := generateFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := string(files[model])
	want := `package fixture

import (
	"strconv"
)

type A int

//mgo:inline stringer A

func (a A) String() string { return strconv.Itoa(int(a)) }

//mgo:end
`
	if got != want {
		t.Fatalf("inline output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestExternalPackageLoadFailureReturnsError(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "model.go"), `package fixture

//mgo:gen describe github.com/guillemus/not-a-real-metago-package.Type

type Local struct{}
`)
	writeTestFile(t, filepath.Join(dir, "templates.metago"), `{{ define "describe" }}
const Name = {{ quote .Name }}
{{ end }}
`)

	_, err := generate(dir)
	if err == nil {
		t.Fatal("expected package load error")
	}
	if !strings.Contains(err.Error(), `load package "github.com/guillemus/not-a-real-metago-package"`) {
		t.Fatalf("expected load package error, got: %v", err)
	}
}

func TestRunResolvesPackageQualifiedTargets(t *testing.T) {
	root := filepath.Join("testdata", "package_targets")
	output := filepath.Join(root, "app", "meta.go")
	_ = os.Remove(output)
	t.Cleanup(func() { _ = os.Remove(output) })

	if err := run(root); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	want := `// Code generated by metago; DO NOT EDIT.

package app

func ShorthandMethodSummary() string {
	return "kind=method type=Server name=Serve params=1 results=1 body=true"
}

func ShorthandFunctionSummary() string {
	return "kind=function type= name=NewServer params=1 results=1 body=true"
}

func FullTypeSummary() string {
	return "kind=struct type=Server name=Server params=0 results=0 body=false"
}

func FullFunctionSummary() string {
	return "kind=function type= name=NewServer params=1 results=1 body=true"
}
`
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestAmbiguousLocalPackageNameErrors(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "go.mod"), "module example.com/ambiguous\n\ngo 1.22\n")
	writeTestFile(t, filepath.Join(root, "app", "app.go"), `package app

//mgo:gen describe api.User

type App struct{}
`)
	writeTestFile(t, filepath.Join(root, "app", "templates.metago"), `{{ define "describe" }}
const Name = {{ quote .Name }}
{{ end }}
`)
	writeTestFile(t, filepath.Join(root, "one", "api.go"), `package api

type User struct{}
`)
	writeTestFile(t, filepath.Join(root, "two", "api.go"), `package api

type User struct{}
`)

	err := run(root)
	if err == nil {
		t.Fatal("expected ambiguous package error")
	}
	if !strings.Contains(err.Error(), `ambiguous package "api"`) {
		t.Fatalf("expected ambiguous package error, got: %v", err)
	}
}

func TestPackageNameTakesPrecedenceOverLocalTypeMethod(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "go.mod"), "module example.com/precedence\n\ngo 1.22\n")
	writeTestFile(t, filepath.Join(root, "api", "api.go"), `package api

type User struct{}
`)
	writeTestFile(t, filepath.Join(root, "app", "app.go"), `package app

//mgo:gen describe api.User

type api struct{}

func (api) User() {}
`)
	writeTestFile(t, filepath.Join(root, "app", "templates.metago"), `{{ define "describe" }}
const Summary = {{ quote (printf "kind=%s name=%s typeName=%s isMethod=%t" .Kind .Name .TypeName .IsMethod) }}
{{ end }}
`)

	if err := run(root); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(root, "app", "meta.go"))
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by metago; DO NOT EDIT.\n\npackage app\n\nconst Summary = \"kind=struct name=User typeName=User isMethod=false\"\n"
	if string(got) != want {
		t.Fatalf("generated output mismatch\n\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(strings.TrimLeft(content, "\n")), 0644); err != nil {
		t.Fatal(err)
	}
}
