// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package serde

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEa16b65cDecodeGithubComGuillemusMetagoExperimentsJson(in *jlexer.Lexer, out *EasyUser) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "age":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Age = int(in.Int())
			}
		case "active":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Active = bool(in.Bool())
			}
		case "score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Score = float64(in.Float64())
			}
		case "tags":
			if in.IsNull() {
				in.Skip()
				out.Tags = nil
			} else {
				in.Delim('[')
				if out.Tags == nil {
					if !in.IsDelim(']') {
						out.Tags = make([]string, 0, 4)
					} else {
						out.Tags = []string{}
					}
				} else {
					out.Tags = (out.Tags)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Tags = append(out.Tags, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Address).UnmarshalEasyJSON(in)
			}
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]EasyItem, 0, 2)
					} else {
						out.Items = []EasyItem{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v2 EasyItem
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Metadata = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v3 string
					if in.IsNull() {
						in.Skip()
					} else {
						v3 = string(in.String())
					}
					(out.Metadata)[key] = v3
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEa16b65cEncodeGithubComGuillemusMetagoExperimentsJson(out *jwriter.Writer, in EasyUser) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"age\":"
		out.RawString(prefix)
		out.Int(int(in.Age))
	}
	{
		const prefix string = ",\"active\":"
		out.RawString(prefix)
		out.Bool(bool(in.Active))
	}
	{
		const prefix string = ",\"score\":"
		out.RawString(prefix)
		out.Float64(float64(in.Score))
	}
	{
		const prefix string = ",\"tags\":"
		out.RawString(prefix)
		if in.Tags == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.Tags {
				if v4 > 0 {
					out.RawByte(',')
				}
				out.String(string(v5))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		(in.Address).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix)
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.Items {
				if v6 > 0 {
					out.RawByte(',')
				}
				(v7).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"metadata\":"
		out.RawString(prefix)
		if in.Metadata == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v8First := true
			for v8Name, v8Value := range in.Metadata {
				if v8First {
					v8First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v8Name))
				out.RawByte(':')
				out.String(string(v8Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EasyUser) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEa16b65cEncodeGithubComGuillemusMetagoExperimentsJson(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EasyUser) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEa16b65cEncodeGithubComGuillemusMetagoExperimentsJson(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EasyUser) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEa16b65cDecodeGithubComGuillemusMetagoExperimentsJson(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EasyUser) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEa16b65cDecodeGithubComGuillemusMetagoExperimentsJson(l, v)
}
func easyjsonEa16b65cDecodeGithubComGuillemusMetagoExperimentsJson1(in *jlexer.Lexer, out *EasyItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sku":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SKU = string(in.String())
			}
		case "qty":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Qty = int(in.Int())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEa16b65cEncodeGithubComGuillemusMetagoExperimentsJson1(out *jwriter.Writer, in EasyItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sku\":"
		out.RawString(prefix[1:])
		out.String(string(in.SKU))
	}
	{
		const prefix string = ",\"qty\":"
		out.RawString(prefix)
		out.Int(int(in.Qty))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EasyItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEa16b65cEncodeGithubComGuillemusMetagoExperimentsJson1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EasyItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEa16b65cEncodeGithubComGuillemusMetagoExperimentsJson1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EasyItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEa16b65cDecodeGithubComGuillemusMetagoExperimentsJson1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EasyItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEa16b65cDecodeGithubComGuillemusMetagoExperimentsJson1(l, v)
}
func easyjsonEa16b65cDecodeGithubComGuillemusMetagoExperimentsJson2(in *jlexer.Lexer, out *EasyFeed) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "users":
			if in.IsNull() {
				in.Skip()
				out.Users = nil
			} else {
				in.Delim('[')
				if out.Users == nil {
					if !in.IsDelim(']') {
						out.Users = make([]EasyUser, 0, 0)
					} else {
						out.Users = []EasyUser{}
					}
				} else {
					out.Users = (out.Users)[:0]
				}
				for !in.IsDelim(']') {
					var v9 EasyUser
					if in.IsNull() {
						in.Skip()
					} else {
						(v9).UnmarshalEasyJSON(in)
					}
					out.Users = append(out.Users, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEa16b65cEncodeGithubComGuillemusMetagoExperimentsJson2(out *jwriter.Writer, in EasyFeed) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"users\":"
		out.RawString(prefix[1:])
		if in.Users == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.Users {
				if v10 > 0 {
					out.RawByte(',')
				}
				(v11).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EasyFeed) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEa16b65cEncodeGithubComGuillemusMetagoExperimentsJson2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EasyFeed) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEa16b65cEncodeGithubComGuillemusMetagoExperimentsJson2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EasyFeed) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEa16b65cDecodeGithubComGuillemusMetagoExperimentsJson2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EasyFeed) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEa16b65cDecodeGithubComGuillemusMetagoExperimentsJson2(l, v)
}
func easyjsonEa16b65cDecodeGithubComGuillemusMetagoExperimentsJson3(in *jlexer.Lexer, out *EasyAddress) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "street":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Street = string(in.String())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
			} else {
				out.City = string(in.String())
			}
		case "zip":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Zip = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEa16b65cEncodeGithubComGuillemusMetagoExperimentsJson3(out *jwriter.Writer, in EasyAddress) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"street\":"
		out.RawString(prefix[1:])
		out.String(string(in.Street))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	{
		const prefix string = ",\"zip\":"
		out.RawString(prefix)
		out.String(string(in.Zip))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EasyAddress) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEa16b65cEncodeGithubComGuillemusMetagoExperimentsJson3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EasyAddress) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEa16b65cEncodeGithubComGuillemusMetagoExperimentsJson3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EasyAddress) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEa16b65cDecodeGithubComGuillemusMetagoExperimentsJson3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EasyAddress) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEa16b65cDecodeGithubComGuillemusMetagoExperimentsJson3(l, v)
}
