// Code generated by metago; DO NOT EDIT.

package serde

import (
	"encoding/json"
	"fmt"
	serdejsonruntime "github.com/guillemus/metago/std/serde/jsonruntime"
	"strconv"
)

// MarshalJSON implements json.Marshaler for User.
func (v User) MarshalJSON() ([]byte, error) {
	return v.appendJSON(make([]byte, 0, 256))
}

func (v User) appendJSON(b []byte) ([]byte, error) {
	b = append(b, '{')
	b = append(b, `"id":`...)
	b = strconv.AppendInt(b, int64(v.ID), 10)
	b = append(b, `,"name":`...)
	b = serdejsonruntime.AppendString(b, v.Name)
	b = append(b, `,"email":`...)
	b = serdejsonruntime.AppendString(b, v.Email)
	b = append(b, `,"age":`...)
	b = strconv.AppendInt(b, int64(v.Age), 10)
	b = append(b, `,"active":`...)
	b = strconv.AppendBool(b, v.Active)
	b = append(b, `,"score":`...)
	b = strconv.AppendFloat(b, v.Score, 'g', -1, 64)
	b = append(b, `,"tags":`...)
	if v.Tags == nil {
		b = append(b, "null"...)
	} else {
		b = append(b, '[')
		for i, e := range v.Tags {
			if i > 0 {
				b = append(b, ',')
			}
			b = serdejsonruntime.AppendString(b, e)
		}
		b = append(b, ']')
	}
	b = append(b, `,"address":`...)
	{
		nb, err := v.Address.appendJSON(b)
		if err != nil {
			return nil, err
		}
		b = nb
	}
	b = append(b, `,"items":`...)
	if v.Items == nil {
		b = append(b, "null"...)
	} else {
		b = append(b, '[')
		for i, e := range v.Items {
			if i > 0 {
				b = append(b, ',')
			}
			nb, err := e.appendJSON(b)
			if err != nil {
				return nil, err
			}
			b = nb
		}
		b = append(b, ']')
	}
	b = append(b, `,"metadata":`...)
	if v.Metadata == nil {
		b = append(b, "null"...)
	} else {
		b = append(b, '{')
		mapFirst := true
		for mk, me := range v.Metadata {
			if !mapFirst {
				b = append(b, ',')
			}
			mapFirst = false
			b = serdejsonruntime.AppendString(b, mk)
			b = append(b, ':')
			b = serdejsonruntime.AppendString(b, me)
		}
		b = append(b, '}')
	}
	b = append(b, '}')
	return b, nil
}

// UnmarshalJSON implements json.Unmarshaler for User.
func (v *User) UnmarshalJSON(data []byte) error {
	l := serdejsonruntime.Lexer{Data: data}
	v.unmarshalJSONLexer(&l)
	if l.Err != nil {
		return l.Err
	}
	l.SkipWS()
	if l.Pos < len(l.Data) {
		return fmt.Errorf("json: trailing data at offset %d", l.Pos)
	}
	return nil
}

func (v *User) unmarshalJSONLexer(l *serdejsonruntime.Lexer) {
	if l.IsNull() {
		return
	}
	l.ObjectOpen()
	for first := true; l.MoreObject(first); first = false {
		switch string(l.KeyBytes()) {
		case "id":
			if !l.IsNull() {
				v.ID = int64(l.Int64())
			}
		case "name":
			if !l.IsNull() {
				v.Name = l.String()
			}
		case "email":
			if !l.IsNull() {
				v.Email = l.String()
			}
		case "age":
			if !l.IsNull() {
				v.Age = int(l.Int64())
			}
		case "active":
			if !l.IsNull() {
				v.Active = l.Bool()
			}
		case "score":
			if !l.IsNull() {
				v.Score = float64(l.Float64())
			}
		case "tags":
			if l.IsNull() {
				v.Tags = nil
			} else {
				if cap(v.Tags) == 0 {
					v.Tags = make([]string, 0, 8)
				} else {
					v.Tags = v.Tags[:0]
				}
				l.ArrayOpen()
				for f := true; l.MoreArray(f); f = false {
					v.Tags = append(v.Tags, l.String())
				}
			}
		case "address":
			v.Address.unmarshalJSONLexer(l)
		case "items":
			if l.IsNull() {
				v.Items = nil
			} else {
				if cap(v.Items) == 0 {
					v.Items = make([]Item, 0, 8)
				} else {
					v.Items = v.Items[:0]
				}
				l.ArrayOpen()
				for f := true; l.MoreArray(f); f = false {
					var e Item
					e.unmarshalJSONLexer(l)
					v.Items = append(v.Items, e)
				}
			}
		case "metadata":
			if l.IsNull() {
				v.Metadata = nil
			} else {
				if v.Metadata == nil {
					v.Metadata = make(map[string]string, 8)
				}
				l.ObjectOpen()
				for f := true; l.MoreObject(f); f = false {
					mk := l.KeyString()
					v.Metadata[mk] = l.String()
				}
			}
		default:
			l.SkipValue()
		}
	}
}

// MarshalJSON implements json.Marshaler for Address.
func (v Address) MarshalJSON() ([]byte, error) {
	return v.appendJSON(make([]byte, 0, 256))
}

func (v Address) appendJSON(b []byte) ([]byte, error) {
	b = append(b, '{')
	b = append(b, `"street":`...)
	b = serdejsonruntime.AppendString(b, v.Street)
	b = append(b, `,"city":`...)
	b = serdejsonruntime.AppendString(b, v.City)
	b = append(b, `,"zip":`...)
	b = serdejsonruntime.AppendString(b, v.Zip)
	b = append(b, '}')
	return b, nil
}

// UnmarshalJSON implements json.Unmarshaler for Address.
func (v *Address) UnmarshalJSON(data []byte) error {
	l := serdejsonruntime.Lexer{Data: data}
	v.unmarshalJSONLexer(&l)
	if l.Err != nil {
		return l.Err
	}
	l.SkipWS()
	if l.Pos < len(l.Data) {
		return fmt.Errorf("json: trailing data at offset %d", l.Pos)
	}
	return nil
}

func (v *Address) unmarshalJSONLexer(l *serdejsonruntime.Lexer) {
	if l.IsNull() {
		return
	}
	l.ObjectOpen()
	for first := true; l.MoreObject(first); first = false {
		switch string(l.KeyBytes()) {
		case "street":
			if !l.IsNull() {
				v.Street = l.String()
			}
		case "city":
			if !l.IsNull() {
				v.City = l.String()
			}
		case "zip":
			if !l.IsNull() {
				v.Zip = l.String()
			}
		default:
			l.SkipValue()
		}
	}
}

// MarshalJSON implements json.Marshaler for Item.
func (v Item) MarshalJSON() ([]byte, error) {
	return v.appendJSON(make([]byte, 0, 256))
}

func (v Item) appendJSON(b []byte) ([]byte, error) {
	b = append(b, '{')
	b = append(b, `"sku":`...)
	b = serdejsonruntime.AppendString(b, v.SKU)
	b = append(b, `,"qty":`...)
	b = strconv.AppendInt(b, int64(v.Qty), 10)
	b = append(b, `,"price":`...)
	b = strconv.AppendFloat(b, v.Price, 'g', -1, 64)
	b = append(b, '}')
	return b, nil
}

// UnmarshalJSON implements json.Unmarshaler for Item.
func (v *Item) UnmarshalJSON(data []byte) error {
	l := serdejsonruntime.Lexer{Data: data}
	v.unmarshalJSONLexer(&l)
	if l.Err != nil {
		return l.Err
	}
	l.SkipWS()
	if l.Pos < len(l.Data) {
		return fmt.Errorf("json: trailing data at offset %d", l.Pos)
	}
	return nil
}

func (v *Item) unmarshalJSONLexer(l *serdejsonruntime.Lexer) {
	if l.IsNull() {
		return
	}
	l.ObjectOpen()
	for first := true; l.MoreObject(first); first = false {
		switch string(l.KeyBytes()) {
		case "sku":
			if !l.IsNull() {
				v.SKU = l.String()
			}
		case "qty":
			if !l.IsNull() {
				v.Qty = int(l.Int64())
			}
		case "price":
			if !l.IsNull() {
				v.Price = float64(l.Float64())
			}
		default:
			l.SkipValue()
		}
	}
}

// MarshalJSON implements json.Marshaler for Feed.
func (v Feed) MarshalJSON() ([]byte, error) {
	return v.appendJSON(make([]byte, 0, 256))
}

func (v Feed) appendJSON(b []byte) ([]byte, error) {
	b = append(b, '{')
	b = append(b, `"users":`...)
	if v.Users == nil {
		b = append(b, "null"...)
	} else {
		b = append(b, '[')
		for i, e := range v.Users {
			if i > 0 {
				b = append(b, ',')
			}
			nb, err := e.appendJSON(b)
			if err != nil {
				return nil, err
			}
			b = nb
		}
		b = append(b, ']')
	}
	b = append(b, '}')
	return b, nil
}

// UnmarshalJSON implements json.Unmarshaler for Feed.
func (v *Feed) UnmarshalJSON(data []byte) error {
	l := serdejsonruntime.Lexer{Data: data}
	v.unmarshalJSONLexer(&l)
	if l.Err != nil {
		return l.Err
	}
	l.SkipWS()
	if l.Pos < len(l.Data) {
		return fmt.Errorf("json: trailing data at offset %d", l.Pos)
	}
	return nil
}

func (v *Feed) unmarshalJSONLexer(l *serdejsonruntime.Lexer) {
	if l.IsNull() {
		return
	}
	l.ObjectOpen()
	for first := true; l.MoreObject(first); first = false {
		switch string(l.KeyBytes()) {
		case "users":
			if l.IsNull() {
				v.Users = nil
			} else {
				if cap(v.Users) == 0 {
					v.Users = make([]User, 0, 8)
				} else {
					v.Users = v.Users[:0]
				}
				l.ArrayOpen()
				for f := true; l.MoreArray(f); f = false {
					var e User
					e.unmarshalJSONLexer(l)
					v.Users = append(v.Users, e)
				}
			}
		default:
			l.SkipValue()
		}
	}
}

// MarshalJSON implements json.Marshaler for CustomJSONEnvelope.
func (v CustomJSONEnvelope) MarshalJSON() ([]byte, error) {
	return v.appendJSON(make([]byte, 0, 256))
}

func (v CustomJSONEnvelope) appendJSON(b []byte) ([]byte, error) {
	b = append(b, '{')
	b = append(b, `"value":`...)
	{
		raw, err := json.Marshal(v.Value)
		if err != nil {
			return nil, err
		}
		b = append(b, raw...)
	}
	b = append(b, `,"pointer":`...)
	{
		raw, err := json.Marshal(v.Pointer)
		if err != nil {
			return nil, err
		}
		b = append(b, raw...)
	}
	b = append(b, '}')
	return b, nil
}

// UnmarshalJSON implements json.Unmarshaler for CustomJSONEnvelope.
func (v *CustomJSONEnvelope) UnmarshalJSON(data []byte) error {
	l := serdejsonruntime.Lexer{Data: data}
	v.unmarshalJSONLexer(&l)
	if l.Err != nil {
		return l.Err
	}
	l.SkipWS()
	if l.Pos < len(l.Data) {
		return fmt.Errorf("json: trailing data at offset %d", l.Pos)
	}
	return nil
}

func (v *CustomJSONEnvelope) unmarshalJSONLexer(l *serdejsonruntime.Lexer) {
	if l.IsNull() {
		return
	}
	l.ObjectOpen()
	for first := true; l.MoreObject(first); first = false {
		switch string(l.KeyBytes()) {
		case "value":
			raw := l.RawValue()
			if l.Err == nil {
				if err := json.Unmarshal(raw, &v.Value); err != nil {
					l.Err = err
				}
			}
		case "pointer":
			raw := l.RawValue()
			if l.Err == nil {
				if err := json.Unmarshal(raw, &v.Pointer); err != nil {
					l.Err = err
				}
			}
		default:
			l.SkipValue()
		}
	}
}

// MarshalJSON implements json.Marshaler for CustomTextEnvelope.
func (v CustomTextEnvelope) MarshalJSON() ([]byte, error) {
	return v.appendJSON(make([]byte, 0, 256))
}

func (v CustomTextEnvelope) appendJSON(b []byte) ([]byte, error) {
	b = append(b, '{')
	b = append(b, `"value":`...)
	{
		raw, err := json.Marshal(v.Value)
		if err != nil {
			return nil, err
		}
		b = append(b, raw...)
	}
	b = append(b, `,"pointer":`...)
	{
		raw, err := json.Marshal(v.Pointer)
		if err != nil {
			return nil, err
		}
		b = append(b, raw...)
	}
	b = append(b, '}')
	return b, nil
}

// UnmarshalJSON implements json.Unmarshaler for CustomTextEnvelope.
func (v *CustomTextEnvelope) UnmarshalJSON(data []byte) error {
	l := serdejsonruntime.Lexer{Data: data}
	v.unmarshalJSONLexer(&l)
	if l.Err != nil {
		return l.Err
	}
	l.SkipWS()
	if l.Pos < len(l.Data) {
		return fmt.Errorf("json: trailing data at offset %d", l.Pos)
	}
	return nil
}

func (v *CustomTextEnvelope) unmarshalJSONLexer(l *serdejsonruntime.Lexer) {
	if l.IsNull() {
		return
	}
	l.ObjectOpen()
	for first := true; l.MoreObject(first); first = false {
		switch string(l.KeyBytes()) {
		case "value":
			raw := l.RawValue()
			if l.Err == nil {
				if err := json.Unmarshal(raw, &v.Value); err != nil {
					l.Err = err
				}
			}
		case "pointer":
			raw := l.RawValue()
			if l.Err == nil {
				if err := json.Unmarshal(raw, &v.Pointer); err != nil {
					l.Err = err
				}
			}
		default:
			l.SkipValue()
		}
	}
}
