// Package serde demonstrates the JSON codec generated by std.serde. The lexer
// runtime and per-type codecs both live in generated meta.go.
package serde

import (
	"encoding/json"
	"strings"
)

//mgo:gen std.serderuntime
//mgo:gen std.serde
type User struct {
	ID       int64             `json:"id"`
	Name     string            `json:"name"`
	Email    string            `json:"email"`
	Age      int               `json:"age"`
	Active   bool              `json:"active"`
	Score    float64           `json:"score"`
	Tags     []string          `json:"tags"`
	Address  Address           `json:"address"`
	Items    []Item            `json:"items"`
	Metadata map[string]string `json:"metadata"`
}

//mgo:gen std.serde
type Address struct {
	Street string `json:"street"`
	City   string `json:"city"`
	Zip    string `json:"zip"`
}

//mgo:gen std.serde
type Item struct {
	SKU   string  `json:"sku"`
	Qty   int     `json:"qty"`
	Price float64 `json:"price"`
}

//mgo:gen std.serde
type Feed struct {
	Users []User `json:"users"`
}

// CustomJSON verifies that generated codecs honor json.Marshaler and json.Unmarshaler on fields.
type CustomJSON string

func (v CustomJSON) MarshalJSON() ([]byte, error) {
	return json.Marshal("marshaled:" + string(v))
}

func (v *CustomJSON) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = CustomJSON(strings.TrimPrefix(value, "marshaled:") + ":unmarshaled")
	return nil
}

//mgo:gen std.serde
type CustomJSONEnvelope struct {
	Value   CustomJSON  `json:"value"`
	Pointer *CustomJSON `json:"pointer"`
}

// CustomText verifies the encoding.TextMarshaler and encoding.TextUnmarshaler fallback paths.
type CustomText string

func (v CustomText) MarshalText() ([]byte, error) {
	return []byte("text:" + string(v)), nil
}

func (v *CustomText) UnmarshalText(data []byte) error {
	*v = CustomText(strings.TrimPrefix(string(data), "text:") + ":unmarshaled")
	return nil
}

//mgo:gen std.serde
type CustomTextEnvelope struct {
	Value   CustomText  `json:"value"`
	Pointer *CustomText `json:"pointer"`
}
