// Package serde demonstrates codecs generated by std.serde using the shared
// generated runtime in the jsonruntime subpackage.
package serde

import (
	"encoding/json"
	"errors"
	"strings"
)

//mgo:gen std.serde
type User struct {
	ID       int64             `json:"id"`
	Name     string            `json:"name"`
	Email    string            `json:"email"`
	Age      int               `json:"age"`
	Active   bool              `json:"active"`
	Score    float64           `json:"score"`
	Tags     []string          `json:"tags"`
	Address  Address           `json:"address"`
	Items    []Item            `json:"items"`
	Metadata map[string]string `json:"metadata"`
}

//mgo:gen std.serde
type Address struct {
	Street string `json:"street"`
	City   string `json:"city"`
	Zip    string `json:"zip"`
}

//mgo:gen std.serde
type Item struct {
	SKU   string  `json:"sku"`
	Qty   int     `json:"qty"`
	Price float64 `json:"price"`
}

//mgo:gen std.serde
type Feed struct {
	Users []User `json:"users"`
}

// CustomJSON verifies that generated codecs honor json.Marshaler and json.Unmarshaler on fields.
type CustomJSON string

func (v CustomJSON) MarshalJSON() ([]byte, error) {
	return json.Marshal("marshaled:" + string(v))
}

func (v *CustomJSON) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = CustomJSON(strings.TrimPrefix(value, "marshaled:") + ":unmarshaled")
	return nil
}

//mgo:gen std.serde
type CustomJSONEnvelope struct {
	Value   CustomJSON  `json:"value"`
	Pointer *CustomJSON `json:"pointer"`
}

// CustomText verifies the encoding.TextMarshaler and encoding.TextUnmarshaler fallback paths.
type CustomText string

func (v CustomText) MarshalText() ([]byte, error) {
	return []byte("text:" + string(v)), nil
}

func (v *CustomText) UnmarshalText(data []byte) error {
	*v = CustomText(strings.TrimPrefix(string(data), "text:") + ":unmarshaled")
	return nil
}

//mgo:gen std.serde
type CustomTextEnvelope struct {
	Value   CustomText  `json:"value"`
	Pointer *CustomText `json:"pointer"`
}

type CustomBoth string

func (CustomBoth) MarshalJSON() ([]byte, error) { return []byte(`"json"`), nil }
func (CustomBoth) MarshalText() ([]byte, error) { return []byte("text"), nil }
func (v *CustomBoth) UnmarshalJSON([]byte) error {
	*v = "json"
	return nil
}
func (v *CustomBoth) UnmarshalText([]byte) error {
	*v = "text"
	return nil
}

//mgo:gen std.serde
type CustomBothEnvelope struct {
	Value   CustomBoth  `json:"value"`
	Pointer *CustomBoth `json:"pointer"`
}

type CustomFailure struct {
	Shared *string
}

func (CustomFailure) MarshalJSON() ([]byte, error) {
	return nil, errors.New("custom marshal failure")
}

func (v *CustomFailure) UnmarshalJSON([]byte) error {
	if v.Shared != nil {
		*v.Shared = "mutated"
	}
	return errors.New("custom unmarshal failure")
}

//mgo:gen std.serde
type CustomFailureEnvelope struct {
	Before  string        `json:"before"`
	Failure CustomFailure `json:"failure"`
}

type NamedString string
type NamedBool bool
type NamedInt int64
type NamedUint uint32
type NamedFloat float32
type NamedByte uint8
type NamedMapKey string

type ZeroByMethod string

func (v ZeroByMethod) IsZero() bool {
	return v == "zero"
}

type ZeroComposite struct {
	Values []int `json:"values"`
}

type TextMapKey struct {
	Value string
}

func (v TextMapKey) MarshalText() ([]byte, error) {
	return []byte("key:" + v.Value), nil
}

func (v *TextMapKey) UnmarshalText(data []byte) error {
	v.Value = strings.TrimPrefix(string(data), "key:")
	return nil
}

//mgo:gen std.serde
type CompatibilityNumbers struct {
	Int8       int8       `json:"int8"`
	Int16      int16      `json:"int16"`
	Int32      int32      `json:"int32"`
	Int64      int64      `json:"int64"`
	Uint8      uint8      `json:"uint8"`
	Uint16     uint16     `json:"uint16"`
	Uint32     uint32     `json:"uint32"`
	Uint64     uint64     `json:"uint64"`
	Float32    float32    `json:"float32"`
	Float64    float64    `json:"float64"`
	Named      NamedInt   `json:"named"`
	NamedUint  NamedUint  `json:"namedUint"`
	NamedFloat NamedFloat `json:"namedFloat"`
}

//mgo:gen std.serde
type CompatibilityValues struct {
	String              string                                    `json:"string"`
	Bool                bool                                      `json:"bool"`
	Pointer             *int                                      `json:"pointer"`
	Nested              **int                                     `json:"nested"`
	StringPointer       *string                                   `json:"stringPointer"`
	Uint8Pointer        *uint8                                    `json:"uint8Pointer"`
	FloatPointer        *float64                                  `json:"floatPointer"`
	NamedStringPtr      *NamedString                              `json:"namedStringPtr"`
	NamedIntNested      **NamedInt                                `json:"namedIntNested"`
	NamedIntTriple      ***NamedInt                               `json:"namedIntTriple"`
	Slice               []int                                     `json:"slice"`
	Int8Slice           []int8                                    `json:"int8Slice"`
	Float32Slice        []float32                                 `json:"float32Slice"`
	NamedStringSlice    []NamedString                             `json:"namedStringSlice"`
	NamedBoolSlice      []NamedBool                               `json:"namedBoolSlice"`
	NamedIntSlice       []NamedInt                                `json:"namedIntSlice"`
	PointerSlice        []*int                                    `json:"pointerSlice"`
	Uint8Pointers       []*uint8                                  `json:"uint8Pointers"`
	FloatPointers       []*float64                                `json:"floatPointers"`
	NamedStringPtrs     []*NamedString                            `json:"namedStringPtrs"`
	NamedIntDoublePtrs  []**NamedInt                              `json:"namedIntDoublePtrs"`
	AddressPointers     []*Address                                `json:"addressPointers"`
	CyclePointers       []*CompatibilityCycle                     `json:"cyclePointers"`
	Array               [3]int                                    `json:"array"`
	Int8Array           [2]int8                                   `json:"int8Array"`
	Float64Array        [2]float64                                `json:"float64Array"`
	NamedUintArray      [2]NamedUint                              `json:"namedUintArray"`
	AddressArray        [2]Address                                `json:"addressArray"`
	Bytes               []byte                                    `json:"bytes"`
	NamedByteSlice      []NamedByte                               `json:"namedByteSlice"`
	Raw                 json.RawMessage                           `json:"raw"`
	Map                 map[string]int                            `json:"map"`
	Int8Map             map[string]int8                           `json:"int8Map"`
	Uint8Map            map[string]uint8                          `json:"uint8Map"`
	Float64Map          map[string]float64                        `json:"float64Map"`
	NamedFloatMap       map[string]NamedFloat                     `json:"namedFloatMap"`
	NamedIntPtrMap      map[string]*NamedInt                      `json:"namedIntPtrMap"`
	NamedIntNestedMap   map[string]**NamedInt                     `json:"namedIntNestedMap"`
	NamedIntTripleMap   map[string]***NamedInt                    `json:"namedIntTripleMap"`
	NamedIntPtrSliceMap map[string][]*NamedInt                    `json:"namedIntPtrSliceMap"`
	RawMap              map[string]json.RawMessage                `json:"rawMap"`
	NamedIntSliceMap    map[string][]NamedInt                     `json:"namedIntSliceMap"`
	ByteSliceMap        map[string][]byte                         `json:"byteSliceMap"`
	NamedByteSliceMap   map[string][]NamedByte                    `json:"namedByteSliceMap"`
	NamedUintArrayMap   map[string][2]NamedUint                   `json:"namedUintArrayMap"`
	NestedScalarMap     map[string]map[NamedMapKey]int8           `json:"nestedScalarMap"`
	AddressSliceMap     map[string][]Address                      `json:"addressSliceMap"`
	AddressPtrSliceMap  map[string][]*Address                     `json:"addressPtrSliceMap"`
	CyclePtrSliceMap    map[string][]*CompatibilityCycle          `json:"cyclePtrSliceMap"`
	AddressArrayMap     map[string][2]Address                     `json:"addressArrayMap"`
	NestedAddressMap    map[string]map[string]Address             `json:"nestedAddressMap"`
	NestedAddressPtrMap map[string]map[string]*Address            `json:"nestedAddressPtrMap"`
	NestedCyclePtrMap   map[string]map[string]*CompatibilityCycle `json:"nestedCyclePtrMap"`
	NamedKeyMap         map[NamedMapKey]string                    `json:"namedKeyMap"`
	TextKeyMap          map[TextMapKey]int                        `json:"textKeyMap"`
	AddressMap          map[string]Address                        `json:"addressMap"`
	AddressPointerMap   map[string]*Address                       `json:"addressPointerMap"`
	CyclePointerMap     map[string]*CompatibilityCycle            `json:"cyclePointerMap"`
	Interface           any                                       `json:"interface"`
	NestedStruct        *CompatibilityTagBehavior                 `json:"nestedStruct"`
}

//mgo:gen std.serde
type CompatibilityTagBehavior struct {
	Renamed       string         `json:"renamed"`
	Ignored       string         `json:"-"`
	EmptyName     string         `json:",omitempty"`
	Punctuation   string         `json:"!#$%&()*+-./:;<=>?@[]^_{|}~"`
	EscapedName   string         `json:"key<&>"`
	OmitString    string         `json:"omitString,omitempty"`
	OmitBool      bool           `json:"omitBool,omitempty"`
	OmitInt       int            `json:"omitInt,omitempty"`
	OmitFloat     float64        `json:"omitFloat,omitempty"`
	OmitPointer   *int           `json:"omitPointer,omitempty"`
	OmitSlice     []int          `json:"omitSlice,omitempty"`
	OmitArray     [0]int         `json:"omitArray,omitempty"`
	OmitMap       map[string]int `json:"omitMap,omitempty"`
	OmitInterface any            `json:"omitInterface,omitempty"`
	ZeroString    string         `json:"zeroString,omitzero"`
	ZeroSlice     []int          `json:"zeroSlice,omitzero"`
	ZeroArray     [2]int         `json:"zeroArray,omitzero"`
	ZeroMethod    ZeroByMethod   `json:"zeroMethod,omitzero"`
	ZeroMethodPtr *ZeroByMethod  `json:"zeroMethodPtr,omitzero"`
	ZeroNamed     NamedInt       `json:"zeroNamed,omitzero"`
	ZeroComposite ZeroComposite  `json:"zeroComposite,omitzero"`
	OmitBoth      []int          `json:"omitBoth,omitempty,omitzero"`
	QuotedString  string         `json:"quotedString,string"`
	QuotedBool    bool           `json:"quotedBool,string"`
	QuotedInt     int            `json:"quotedInt,string"`
	QuotedUint    uint64         `json:"quotedUint,string"`
	QuotedFloat   float64        `json:"quotedFloat,string"`
	QuotedNamed   NamedInt       `json:"quotedNamed,string"`
	Named         NamedString    `json:"named"`
	Unexported    string         `json:"unexported"`
	hidden        string
}

type CompatibilityEmbedded struct {
	Promoted string `json:"promoted"`
	Conflict string `json:"conflict"`
}

//mgo:gen std.serde
type CompatibilityEmbedding struct {
	CompatibilityEmbedded
	Conflict string `json:"conflict"`
}

type CompatibilityConflictA struct {
	Conflict string `json:"conflict"`
	Plain    string
}

type CompatibilityConflictB struct {
	Conflict string `json:"conflict"`
	Tagged   string `json:"Plain"`
}

type CompatibilityAnonymousValue struct {
	Name string     `json:"name"`
	Both CustomBoth `json:"both"`
	JSON CustomJSON `json:"json"`
	Text CustomText `json:"text"`
}

type CompatibilityAnonymousPointer struct {
	Count int `json:"count"`
}

//mgo:gen std.serde
type CompatibilityAnonymous struct {
	CompatibilityAnonymousValue    `json:"value"`
	*CompatibilityAnonymousPointer `json:"pointer,omitempty"`
	Tail                           int `json:"tail"`
}

//mgo:gen std.serde
type CompatibilityAnonymousPromotion struct {
	*CompatibilityEmbedded
	Outer string `json:"outer"`
}

//mgo:gen std.serde
type CompatibilityDominance struct {
	CompatibilityConflictA
	CompatibilityConflictB
}

//mgo:gen std.serde
type CompatibilityCycle struct {
	Value string              `json:"value"`
	Next  *CompatibilityCycle `json:"next"`
}

//mgo:gen std.serde strict=true
type StrictValues struct {
	Name string `json:"name"`
}

//mgo:gen std.serde maxinput=32
type LimitedInput struct {
	Name string `json:"name"`
}

//mgo:gen std.serde maxdepth=4
type LimitedDepth struct {
	Name string        `json:"name"`
	Next *LimitedDepth `json:"next"`
}
