// Package serde demonstrates codecs generated by std.serde.json using the shared
// generated runtime in the jsonruntime subpackage.
package serde

import (
	"encoding/json"
	"errors"
	"strings"
)

//mgo:gen std.serde.json
type User struct {
	ID       int64             `json:"id"`
	Name     string            `json:"name"`
	Email    string            `json:"email"`
	Age      int               `json:"age"`
	Active   bool              `json:"active"`
	Score    float64           `json:"score"`
	Tags     []string          `json:"tags"`
	Address  Address           `json:"address"`
	Items    []Item            `json:"items"`
	Metadata map[string]string `json:"metadata"`
}

//mgo:gen std.serde.json
type Address struct {
	Street string `json:"street"`
	City   string `json:"city"`
	Zip    string `json:"zip"`
}

//mgo:gen std.serde.json
type Item struct {
	SKU   string  `json:"sku"`
	Qty   int     `json:"qty"`
	Price float64 `json:"price"`
}

//mgo:gen std.serde.json
type Feed struct {
	Users []User `json:"users"`
}

// CustomJSON verifies that generated codecs honor json.Marshaler and json.Unmarshaler on fields.
type CustomJSON string

func (v CustomJSON) MarshalJSON() ([]byte, error) {
	return json.Marshal("marshaled:" + string(v))
}

func (v *CustomJSON) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = CustomJSON(strings.TrimPrefix(value, "marshaled:") + ":unmarshaled")
	return nil
}

//mgo:gen std.serde.json
type CustomJSONEnvelope struct {
	Value   CustomJSON  `json:"value"`
	Pointer *CustomJSON `json:"pointer"`
}

// CustomText verifies the encoding.TextMarshaler and encoding.TextUnmarshaler fallback paths.
type CustomText string

func (v CustomText) MarshalText() ([]byte, error) {
	return []byte("text:" + string(v)), nil
}

func (v *CustomText) UnmarshalText(data []byte) error {
	*v = CustomText(strings.TrimPrefix(string(data), "text:") + ":unmarshaled")
	return nil
}

//mgo:gen std.serde.json
type CustomTextEnvelope struct {
	Value   CustomText  `json:"value"`
	Pointer *CustomText `json:"pointer"`
}

type CustomBoth string

func (CustomBoth) MarshalJSON() ([]byte, error) { return []byte(`"json"`), nil }
func (CustomBoth) MarshalText() ([]byte, error) { return []byte("text"), nil }
func (v *CustomBoth) UnmarshalJSON([]byte) error {
	*v = "json"
	return nil
}
func (v *CustomBoth) UnmarshalText([]byte) error {
	*v = "text"
	return nil
}

//mgo:gen std.serde.json
type CustomBothEnvelope struct {
	Value   CustomBoth  `json:"value"`
	Pointer *CustomBoth `json:"pointer"`
}

type CustomFailure struct {
	Shared *string
}

func (CustomFailure) MarshalJSON() ([]byte, error) {
	return nil, errors.New("custom marshal failure")
}

func (v *CustomFailure) UnmarshalJSON([]byte) error {
	if v.Shared != nil {
		*v.Shared = "mutated"
	}
	return errors.New("custom unmarshal failure")
}

//mgo:gen std.serde.json
type CustomFailureEnvelope struct {
	Before  string        `json:"before"`
	Failure CustomFailure `json:"failure"`
}

type NamedString string
type NamedInt int64
type NamedUint uint32
type NamedFloat float32
type NamedMapKey string

//mgo:gen std.serde.json
type CompatibilityNumbers struct {
	Int8       int8       `json:"int8"`
	Int16      int16      `json:"int16"`
	Int32      int32      `json:"int32"`
	Int64      int64      `json:"int64"`
	Uint8      uint8      `json:"uint8"`
	Uint16     uint16     `json:"uint16"`
	Uint32     uint32     `json:"uint32"`
	Uint64     uint64     `json:"uint64"`
	Float32    float32    `json:"float32"`
	Float64    float64    `json:"float64"`
	Named      NamedInt   `json:"named"`
	NamedUint  NamedUint  `json:"namedUint"`
	NamedFloat NamedFloat `json:"namedFloat"`
}

//mgo:gen std.serde.json
type CompatibilityValues struct {
	String       string                    `json:"string"`
	Bool         bool                      `json:"bool"`
	Pointer      *int                      `json:"pointer"`
	Nested       **int                     `json:"nested"`
	Slice        []int                     `json:"slice"`
	Array        [3]int                    `json:"array"`
	Bytes        []byte                    `json:"bytes"`
	Raw          json.RawMessage           `json:"raw"`
	Map          map[string]int            `json:"map"`
	NamedKeyMap  map[NamedMapKey]string    `json:"namedKeyMap"`
	Interface    any                       `json:"interface"`
	NestedStruct *CompatibilityTagBehavior `json:"nestedStruct"`
}

//mgo:gen std.serde.json
type CompatibilityTagBehavior struct {
	Renamed       string         `json:"renamed"`
	Ignored       string         `json:"-"`
	EmptyName     string         `json:",omitempty"`
	Punctuation   string         `json:"!#$%&()*+-./:;<=>?@[]^_{|}~"`
	EscapedName   string         `json:"key<&>"`
	OmitString    string         `json:"omitString,omitempty"`
	OmitBool      bool           `json:"omitBool,omitempty"`
	OmitInt       int            `json:"omitInt,omitempty"`
	OmitFloat     float64        `json:"omitFloat,omitempty"`
	OmitPointer   *int           `json:"omitPointer,omitempty"`
	OmitSlice     []int          `json:"omitSlice,omitempty"`
	OmitArray     [0]int         `json:"omitArray,omitempty"`
	OmitMap       map[string]int `json:"omitMap,omitempty"`
	OmitInterface any            `json:"omitInterface,omitempty"`
	QuotedInt     int            `json:"quotedInt,string"`
	Named         NamedString    `json:"named"`
	Unexported    string         `json:"unexported"`
	hidden        string
}

type CompatibilityEmbedded struct {
	Promoted string `json:"promoted"`
	Conflict string `json:"conflict"`
}

//mgo:gen std.serde.json
type CompatibilityEmbedding struct {
	CompatibilityEmbedded
	Conflict string `json:"conflict"`
}

type CompatibilityConflictA struct {
	Conflict string `json:"conflict"`
	Plain    string
}

type CompatibilityConflictB struct {
	Conflict string `json:"conflict"`
	Tagged   string `json:"Plain"`
}

//mgo:gen std.serde.json
type CompatibilityDominance struct {
	CompatibilityConflictA
	CompatibilityConflictB
}

//mgo:gen std.serde.json
type CompatibilityCycle struct {
	Value string              `json:"value"`
	Next  *CompatibilityCycle `json:"next"`
}
