// Code generated by metago; DO NOT EDIT.

package enum

const (
	ArticleStatusDraft     ArticleStatus = "draft"
	ArticleStatusPublished ArticleStatus = "published"
	ArticleStatusArchived  ArticleStatus = "archived"
)

func (v ArticleStatus) String() string { return string(v) }
