// Code generated by metago; DO NOT EDIT.

package mapstruct

import (
	"fmt"
)

func mapstructureDecodeField[T any](input map[string]any, key string, destination *T, required bool) error {
	value, exists := input[key]
	if !exists {
		if required {
			return fmt.Errorf("field %q is required", key)
		}
		return nil
	}
	typed, ok := value.(T)
	if !ok {
		var expected T
		return fmt.Errorf("field %q must be %T", key, expected)
	}
	*destination = typed
	return nil
}

func (v *User) Decode(input map[string]any) error {
	next := *v
	if err := mapstructureDecodeField(input, "id", &next.ID, true); err != nil {
		return err
	}
	if err := mapstructureDecodeField(input, "display_name", &next.Name, true); err != nil {
		return err
	}
	if value, exists := input["address"]; exists {
		nested, ok := value.(map[string]any)
		if !ok {
			return fmt.Errorf("field %q must be an object", "address")
		}
		if err := mapstructureDecodeField(nested, "city", &next.Address.City, true); err != nil {
			return err
		}
		if err := mapstructureDecodeField(nested, "country", &next.Address.Country, true); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("field %q is required", "address")
	}
	*v = next
	return nil
}

func (v *User) Encode() map[string]any {
	return map[string]any{
		"id":           v.ID,
		"display_name": v.Name,
		"address": map[string]any{
			"city":    v.Address.City,
			"country": v.Address.Country,
		},
	}
}

func (v *Preferences) Decode(input map[string]any) error {
	next := *v
	if err := mapstructureDecodeField(input, "theme", &next.Theme, false); err != nil {
		return err
	}
	if err := mapstructureDecodeField(input, "locale", &next.Locale, true); err != nil {
		return err
	}
	*v = next
	return nil
}

func (v *Preferences) Encode() map[string]any {
	return map[string]any{
		"theme":  v.Theme,
		"locale": v.Locale,
	}
}
