// Code generated by metago; DO NOT EDIT.

package mapstruct

import (
	"fmt"
)

func (v *User) Decode(input map[string]any) error {
	next := *v
	if value, exists := input["id"]; exists {
		typed, ok := value.(string)
		if !ok {
			return fmt.Errorf("field %q must be string", "id")
		}
		next.ID = typed
	} else if true {
		return fmt.Errorf("field %q is required", "id")
	}
	if value, exists := input["display_name"]; exists {
		typed, ok := value.(string)
		if !ok {
			return fmt.Errorf("field %q must be string", "display_name")
		}
		next.Name = typed
	} else if true {
		return fmt.Errorf("field %q is required", "display_name")
	}
	if value, exists := input["address"]; exists {
		nested, ok := value.(map[string]any)
		if !ok {
			return fmt.Errorf("field %q must be an object", "address")
		}
		if value, exists := nested["city"]; exists {
			typed, ok := value.(string)
			if !ok {
				return fmt.Errorf("field %q must be string", "address.city")
			}
			next.Address.City = typed
		} else if true {
			return fmt.Errorf("field %q is required", "address.city")
		}
		if value, exists := nested["country"]; exists {
			typed, ok := value.(string)
			if !ok {
				return fmt.Errorf("field %q must be string", "address.country")
			}
			next.Address.Country = typed
		} else if true {
			return fmt.Errorf("field %q is required", "address.country")
		}
	} else if true {
		return fmt.Errorf("field %q is required", "address")
	}
	*v = next
	return nil
}

func (v *User) Encode() map[string]any {
	return map[string]any{
		"id":           v.ID,
		"display_name": v.Name,
		"address": map[string]any{
			"city":    v.Address.City,
			"country": v.Address.Country,
		},
	}
}

func (v *Preferences) Decode(input map[string]any) error {
	next := *v
	if value, exists := input["theme"]; exists {
		typed, ok := value.(string)
		if !ok {
			return fmt.Errorf("field %q must be string", "theme")
		}
		next.Theme = typed
	} else if false {
		return fmt.Errorf("field %q is required", "theme")
	}
	if value, exists := input["locale"]; exists {
		typed, ok := value.(string)
		if !ok {
			return fmt.Errorf("field %q must be string", "locale")
		}
		next.Locale = typed
	} else if true {
		return fmt.Errorf("field %q is required", "locale")
	}
	*v = next
	return nil
}

func (v *Preferences) Encode() map[string]any {
	return map[string]any{
		"theme":  v.Theme,
		"locale": v.Locale,
	}
}
