// Code generated by metago; DO NOT EDIT.

package jsonruntime

import (
	"bytes"
	"fmt"
	"math"
	"strconv"
	"unicode/utf16"
	"unicode/utf8"
)

// Lexer is a cursor over the input buffer. All methods are no-ops after
// the first error, so generated code never checks errors mid-parse.
type Lexer struct {
	Data []byte
	// Text is a lazily created string copy of Data. Retained strings are
	// substrings of it, so a whole parse costs one string allocation instead
	// of one per value. The trade-off: any retained string pins the full copy.
	Text string
	Pos  int
	Err  error
}

func (l *Lexer) Fail(msg string) {
	if l.Err == nil {
		l.Err = fmt.Errorf("json: %s at offset %d", msg, l.Pos)
	}
}

func (l *Lexer) SkipWS() {
	for l.Pos < len(l.Data) {
		c := l.Data[l.Pos]
		if c != ' ' && c != '\t' && c != '\n' && c != '\r' {
			return
		}
		l.Pos++
	}
}

// Expect takes the failure message as a caller-provided constant so the
// success path never builds a string.
func (l *Lexer) Expect(c byte, what string) {
	if l.Err != nil {
		return
	}
	l.SkipWS()
	if l.Pos < len(l.Data) && l.Data[l.Pos] == c {
		l.Pos++
		return
	}
	l.Fail("expected " + what)
}

func (l *Lexer) ObjectOpen() { l.Expect('{', "'{'") }
func (l *Lexer) ArrayOpen()  { l.Expect('[', "'['") }

func (l *Lexer) MoreObject(first bool) bool {
	return l.More(first, '}')
}

func (l *Lexer) MoreArray(first bool) bool {
	return l.More(first, ']')
}

func (l *Lexer) More(first bool, close byte) bool {
	if l.Err != nil {
		return false
	}
	l.SkipWS()
	if l.Pos >= len(l.Data) {
		l.Fail("unexpected end of input")
		return false
	}
	if l.Data[l.Pos] == close {
		l.Pos++
		return false
	}
	if !first {
		if l.Data[l.Pos] != ',' {
			l.Fail("expected ','")
			return false
		}
		l.Pos++
		l.SkipWS()
		if l.Pos < len(l.Data) && l.Data[l.Pos] == close {
			l.Fail("trailing comma")
			return false
		}
	}
	return true
}

// KeyBytes returns the next object key. The result may alias the input buffer.
func (l *Lexer) KeyBytes() []byte {
	b := l.StringBytes()
	l.Expect(':', "':'")
	return b
}

// StringBytes parses a JSON string. When the string has no escapes it returns a
// sub-slice of the input without copying.
func (l *Lexer) StringBytes() []byte {
	if l.Err != nil {
		return nil
	}
	l.SkipWS()
	if l.Pos >= len(l.Data) || l.Data[l.Pos] != '"' {
		l.Fail("expected string")
		return nil
	}
	l.Pos++
	start := l.Pos
	quote := bytes.IndexByte(l.Data[l.Pos:], '"')
	if quote < 0 {
		l.Fail("unterminated string")
		return nil
	}
	if bytes.IndexByte(l.Data[l.Pos:l.Pos+quote], '\\') < 0 {
		l.Pos += quote + 1
		return l.Data[start : start+quote]
	}
	return l.StringSlow()
}

// String returns the parsed string, safe to retain after the parse. Strings
// without escapes are substrings of the shared text copy — no per-value
// allocation.
func (l *Lexer) String() string {
	if l.Err != nil {
		return ""
	}
	l.SkipWS()
	if l.Pos >= len(l.Data) || l.Data[l.Pos] != '"' {
		l.Fail("expected string")
		return ""
	}
	l.Pos++
	start := l.Pos
	quote := bytes.IndexByte(l.Data[l.Pos:], '"')
	if quote < 0 {
		l.Fail("unterminated string")
		return ""
	}
	if bytes.IndexByte(l.Data[l.Pos:l.Pos+quote], '\\') < 0 {
		l.Pos += quote + 1
		if l.Text == "" {
			l.Text = string(l.Data)
		}
		return l.Text[start : start+quote]
	}
	return string(l.StringSlow())
}

// KeyString returns the next object key as a retained string, for map keys.
func (l *Lexer) KeyString() string {
	s := l.String()
	l.Expect(':', "':'")
	return s
}

func (l *Lexer) StringSlow() []byte {
	buf := make([]byte, 0, 64)
	for l.Pos < len(l.Data) {
		c := l.Data[l.Pos]
		if c == '"' {
			l.Pos++
			return buf
		}
		if c != '\\' {
			buf = append(buf, c)
			l.Pos++
			continue
		}
		l.Pos++
		if l.Pos >= len(l.Data) {
			break
		}
		esc := l.Data[l.Pos]
		l.Pos++
		switch esc {
		case '"', '\\', '/':
			buf = append(buf, esc)
		case 'b':
			buf = append(buf, '\b')
		case 'f':
			buf = append(buf, '\f')
		case 'n':
			buf = append(buf, '\n')
		case 'r':
			buf = append(buf, '\r')
		case 't':
			buf = append(buf, '\t')
		case 'u':
			r := rune(l.Hex4())
			if utf16.IsSurrogate(r) {
				if l.Pos+1 < len(l.Data) && l.Data[l.Pos] == '\\' && l.Data[l.Pos+1] == 'u' {
					l.Pos += 2
					r = utf16.DecodeRune(r, rune(l.Hex4()))
				} else {
					r = utf8.RuneError
				}
			}
			buf = utf8.AppendRune(buf, r)
		default:
			l.Fail("invalid escape")
			return nil
		}
	}
	l.Fail("unterminated string")
	return nil
}

func (l *Lexer) Hex4() uint32 {
	if l.Pos+4 > len(l.Data) {
		l.Fail("invalid \\u escape")
		return 0
	}
	var r uint32
	for i := range 4 {
		c := l.Data[l.Pos+i]
		switch {
		case c >= '0' && c <= '9':
			r = r<<4 | uint32(c-'0')
		case c >= 'a' && c <= 'f':
			r = r<<4 | uint32(c-'a'+10)
		case c >= 'A' && c <= 'F':
			r = r<<4 | uint32(c-'A'+10)
		default:
			l.Fail("invalid \\u escape")
			return 0
		}
	}
	l.Pos += 4
	return r
}

// IsNull consumes a null literal if present. Generated code uses it to match
// encoding/json semantics: null leaves the field untouched.
func (l *Lexer) IsNull() bool {
	if l.Err != nil {
		return false
	}
	l.SkipWS()
	if l.Pos+4 <= len(l.Data) && string(l.Data[l.Pos:l.Pos+4]) == "null" {
		l.Pos += 4
		return true
	}
	return false
}

func (l *Lexer) Bool() bool {
	if l.Err != nil {
		return false
	}
	l.SkipWS()
	if l.Pos+4 <= len(l.Data) && string(l.Data[l.Pos:l.Pos+4]) == "true" {
		l.Pos += 4
		return true
	}
	if l.Pos+5 <= len(l.Data) && string(l.Data[l.Pos:l.Pos+5]) == "false" {
		l.Pos += 5
		return false
	}
	l.Fail("expected Bool")
	return false
}

func (l *Lexer) Int64() int64 {
	if l.Err != nil {
		return 0
	}
	l.SkipWS()
	neg := false
	if l.Pos < len(l.Data) && l.Data[l.Pos] == '-' {
		neg = true
		l.Pos++
	}
	n := l.Uint64()
	if l.Err != nil {
		return 0
	}
	if neg {
		if n > 1<<63 {
			l.Fail("integer overflow")
			return 0
		}
		return -int64(n)
	}
	if n > math.MaxInt64 {
		l.Fail("integer overflow")
		return 0
	}
	return int64(n)
}

func (l *Lexer) Uint64() uint64 {
	if l.Err != nil {
		return 0
	}
	l.SkipWS()
	start := l.Pos
	var n uint64
	for l.Pos < len(l.Data) {
		c := l.Data[l.Pos]
		if c < '0' || c > '9' {
			break
		}
		d := uint64(c - '0')
		if n > (math.MaxUint64-d)/10 {
			l.Fail("integer overflow")
			return 0
		}
		n = n*10 + d
		l.Pos++
	}
	if l.Pos == start {
		l.Fail("expected integer")
		return 0
	}
	if l.Pos < len(l.Data) {
		c := l.Data[l.Pos]
		if c == '.' || c == 'e' || c == 'E' {
			l.Fail("expected integer, found number")
			return 0
		}
	}
	return n
}

var jsonPow10 = [...]float64{
	1, 1e1, 1e2, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e9, 1e10, 1e11,
	1e12, 1e13, 1e14, 1e15, 1e16, 1e17, 1e18, 1e19, 1e20, 1e21, 1e22,
}

// float64 parses simple decimals directly. A mantissa of up to 15 digits is
// exact in a float64, and dividing by an exact power of ten rounds once, so the
// result matches strconv.ParseFloat. Exponents, long mantissas, and overflow
// take the ParseFloat path.
func (l *Lexer) Float64() float64 {
	if l.Err != nil {
		return 0
	}
	l.SkipWS()
	start := l.Pos
	pos := l.Pos
	data := l.Data
	neg := false
	if pos < len(data) && data[pos] == '-' {
		pos++
		neg = true
	}
	var mant uint64
	digits := 0
	overflow := false
	for pos < len(data) && data[pos] >= '0' && data[pos] <= '9' {
		if mant > (math.MaxUint64-9)/10 {
			overflow = true
		}
		mant = mant*10 + uint64(data[pos]-'0')
		digits++
		pos++
	}
	frac := 0
	if pos < len(data) && data[pos] == '.' {
		pos++
		for pos < len(data) && data[pos] >= '0' && data[pos] <= '9' {
			if mant > (math.MaxUint64-9)/10 {
				overflow = true
			}
			mant = mant*10 + uint64(data[pos]-'0')
			digits++
			frac++
			pos++
		}
	}
	if digits == 0 {
		l.Fail("expected number")
		return 0
	}
	if pos < len(data) && (data[pos] == 'e' || data[pos] == 'E') {
		pos++
		if pos < len(data) && (data[pos] == '-' || data[pos] == '+') {
			pos++
		}
		expStart := pos
		for pos < len(data) && data[pos] >= '0' && data[pos] <= '9' {
			pos++
		}
		if pos == expStart {
			l.Fail("invalid number")
			return 0
		}
		return l.FloatSlow(start, pos)
	}
	if overflow || digits > 15 {
		return l.FloatSlow(start, pos)
	}
	l.Pos = pos
	f := float64(mant)
	if frac > 0 {
		f /= jsonPow10[frac]
	}
	if neg {
		f = -f
	}
	return f
}

func (l *Lexer) FloatSlow(start, end int) float64 {
	f, err := strconv.ParseFloat(string(l.Data[start:end]), 64)
	if err != nil {
		l.Fail("invalid number")
		return 0
	}
	l.Pos = end
	return f
}

// SkipValue advances past one JSON value of any shape without decoding it.
func (l *Lexer) SkipValue() {
	if l.Err != nil {
		return
	}
	l.SkipWS()
	if l.Pos >= len(l.Data) {
		l.Fail("unexpected end of input")
		return
	}
	switch l.Data[l.Pos] {
	case '"':
		l.StringBytes()
	case '{', '[':
		depth := 0
		for l.Pos < len(l.Data) && l.Err == nil {
			switch l.Data[l.Pos] {
			case '"':
				l.StringBytes()
				continue
			case '{', '[':
				depth++
			case '}', ']':
				depth--
				if depth == 0 {
					l.Pos++
					return
				}
			}
			l.Pos++
		}
		if l.Err == nil {
			l.Fail("unterminated value")
		}
	default:
		for l.Pos < len(l.Data) {
			switch l.Data[l.Pos] {
			case ',', '}', ']', ' ', '\t', '\n', '\r':
				return
			}
			l.Pos++
		}
	}
}

// RawValue returns the raw bytes of the next value, for encoding/json
// fallbacks on field types the generator does not handle natively.
func (l *Lexer) RawValue() []byte {
	if l.Err != nil {
		return nil
	}
	l.SkipWS()
	start := l.Pos
	l.SkipValue()
	if l.Err != nil {
		return nil
	}
	return l.Data[start:l.Pos]
}

const jsonHexDigits = "0123456789abcdef"

func AppendString(dst []byte, s string) []byte {
	dst = append(dst, '"')
	start := 0
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c >= 0x20 && c != '"' && c != '\\' {
			continue
		}
		dst = append(dst, s[start:i]...)
		switch c {
		case '"':
			dst = append(dst, '\\', '"')
		case '\\':
			dst = append(dst, '\\', '\\')
		case '\n':
			dst = append(dst, '\\', 'n')
		case '\r':
			dst = append(dst, '\\', 'r')
		case '\t':
			dst = append(dst, '\\', 't')
		default:
			dst = append(dst, '\\', 'u', '0', '0', jsonHexDigits[c>>4], jsonHexDigits[c&0xF])
		}
		start = i + 1
	}
	dst = append(dst, s[start:]...)
	return append(dst, '"')
}
