// Code generated by metago; DO NOT EDIT.

package jsonruntime

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"math"
	"strconv"
	"strings"
	"unicode/utf16"
	"unicode/utf8"
)

// Lexer is a cursor over the input buffer. All methods are no-ops after
// the first error, so generated code never checks errors mid-parse.
type Lexer struct {
	Data       []byte
	Pos        int
	Err        error
	Depth      uint64
	MaxDepth   uint64
	strings    strings.Builder
	ownStrings bool
}

// EnableStringArena makes retained decoded strings share one owned buffer.
// Generated root decoders call it once; nested codecs automatically reuse it.
func (l *Lexer) EnableStringArena(capacity int) {
	l.ownStrings = true
	if capacity > 0 {
		l.strings.Grow(capacity)
	}
}

func (l *Lexer) Fail(msg string) {
	if l.Err == nil {
		l.Err = fmt.Errorf("json: %s at offset %d", msg, l.Pos)
	}
}

const defaultMaxJSONDepth uint64 = 10000

func (l *Lexer) depthLimit() uint64 {
	if l.MaxDepth != 0 {
		return l.MaxDepth
	}
	return defaultMaxJSONDepth
}

// EnterValue accounts for generated recursive values. SkipValue and raw-value
// parsing add their local structural depth to the same counter.
func (l *Lexer) EnterValue() bool {
	if l.Err != nil {
		return false
	}
	if l.Depth >= l.depthLimit() {
		l.Fail("maximum nesting depth exceeded")
		return false
	}
	l.Depth++
	return true
}

func (l *Lexer) LeaveValue() {
	if l.Depth > 0 {
		l.Depth--
	}
}

// WrapField adds generated Go-field and JSON-kind context while preserving
// the original syntax/type error and its byte offset.
func (l *Lexer) WrapField(name, goType string, valueOffset int) {
	if l.Err != nil {
		l.Err = fmt.Errorf("field %q (Go type %s, JSON %s) near offset %d: %w", name, goType, l.KindAt(valueOffset), l.Pos, l.Err)
	}
}

func (l *Lexer) KindAt(pos int) string {
	for pos < len(l.Data) {
		switch l.Data[pos] {
		case ' ', '\t', '\n', '\r':
			pos++
			continue
		case '"':
			return "string"
		case '{':
			return "object"
		case '[':
			return "array"
		case 't', 'f':
			return "boolean"
		case 'n':
			return "null"
		default:
			if l.Data[pos] == '-' || l.Data[pos] >= '0' && l.Data[pos] <= '9' {
				return "number"
			}
			return "invalid token"
		}
	}
	return "end of input"
}

func (l *Lexer) SkipWS() {
	if l.Pos < len(l.Data) && l.Data[l.Pos] > ' ' {
		return
	}
	for l.Pos < len(l.Data) {
		c := l.Data[l.Pos]
		if c != ' ' && c != '\t' && c != '\n' && c != '\r' {
			return
		}
		l.Pos++
	}
}

// Expect takes the failure message as a caller-provided constant so the
// success path never builds a string.
func (l *Lexer) Expect(c byte, what string) {
	if l.Err != nil {
		return
	}
	l.SkipWS()
	if l.Pos < len(l.Data) && l.Data[l.Pos] == c {
		l.Pos++
		return
	}
	l.Fail("expected " + what)
}

func (l *Lexer) ObjectOpen() {
	if l.Err == nil && l.Pos < len(l.Data) && l.Data[l.Pos] == '{' {
		l.Pos++
		return
	}
	l.Expect('{', "'{'")
}

func (l *Lexer) ArrayOpen() {
	if l.Err == nil && l.Pos < len(l.Data) && l.Data[l.Pos] == '[' {
		l.Pos++
		return
	}
	l.Expect('[', "'['")
}

func (l *Lexer) Colon() {
	if l.Err == nil && l.Pos < len(l.Data) && l.Data[l.Pos] == ':' {
		l.Pos++
		return
	}
	l.Expect(':', "':'")
}

func (l *Lexer) MoreObject(first bool) bool {
	return l.More(first, '}')
}

func (l *Lexer) MoreArray(first bool) bool {
	return l.More(first, ']')
}

func (l *Lexer) More(first bool, close byte) bool {
	if l.Err != nil {
		return false
	}
	if l.Pos < len(l.Data) {
		c := l.Data[l.Pos]
		if c == close {
			l.Pos++
			return false
		}
		if first {
			if c != ' ' && c != '\t' && c != '\n' && c != '\r' {
				return true
			}
		} else if c == ',' && l.Pos+1 < len(l.Data) {
			next := l.Data[l.Pos+1]
			if next == close {
				l.Pos++
				l.Fail("trailing comma")
				return false
			}
			if next != ' ' && next != '\t' && next != '\n' && next != '\r' {
				l.Pos++
				return true
			}
		}
	}
	l.SkipWS()
	if l.Pos >= len(l.Data) {
		l.Fail("unexpected end of input")
		return false
	}
	if l.Data[l.Pos] == close {
		l.Pos++
		return false
	}
	if !first {
		if l.Data[l.Pos] != ',' {
			l.Fail("expected ','")
			return false
		}
		l.Pos++
		l.SkipWS()
		if l.Pos < len(l.Data) && l.Data[l.Pos] == close {
			l.Fail("trailing comma")
			return false
		}
	}
	return true
}

// KeyBytes returns the next object key. The result may alias the input buffer.
func (l *Lexer) KeyBytes() []byte {
	key := l.StringBytes()
	l.Colon()
	return key
}

// StringBytes parses a JSON string. Unescaped valid UTF-8 aliases the input;
// escaped or malformed UTF-8 input is normalized into a new buffer.
func (l *Lexer) StringBytes() []byte {
	if l.Err != nil {
		return nil
	}
	l.SkipWS()
	if l.Pos >= len(l.Data) || l.Data[l.Pos] != '"' {
		l.Fail("expected string")
		return nil
	}
	l.Pos++
	start := l.Pos
	quote := bytes.IndexByte(l.Data[l.Pos:], '"')
	if quote < 0 {
		l.Fail("unterminated string")
		return nil
	}
	plain := l.Data[l.Pos : l.Pos+quote]
	ascii := true
	escaped := false
	for _, c := range plain {
		if c == '\\' {
			escaped = true
			break
		}
		if c < 0x20 {
			l.Fail("unescaped control character in string")
			return nil
		}
		if c >= utf8.RuneSelf {
			ascii = false
		}
	}
	if !escaped {
		l.Pos += quote + 1
		if ascii || utf8.Valid(plain) {
			return l.Data[start : start+quote]
		}
		return bytes.ToValidUTF8(plain, []byte(string(utf8.RuneError)))
	}
	return l.StringSlow()
}

// String returns an independent string that is safe to retain or use after
// the caller reuses the input buffer.
func (l *Lexer) String() string {
	if !l.ownStrings {
		return string(l.StringBytes())
	}
	if l.Err != nil {
		return ""
	}
	l.SkipWS()
	stringStart := l.Pos
	if stringStart >= len(l.Data) || l.Data[stringStart] != '"' {
		l.Fail("expected string")
		return ""
	}
	valueStart := stringStart + 1
	for i := valueStart; i < len(l.Data); i++ {
		c := l.Data[i]
		switch {
		case c == '"':
			l.Pos = i + 1
			return l.retainString(l.Data[valueStart:i])
		case c == '\\' || c >= utf8.RuneSelf:
			// Keep the complete escape and UTF-8 normalization path for the
			// uncommon case, but avoid its extra scan for ordinary ASCII.
			l.Pos = stringStart
			return l.retainString(l.StringBytes())
		case c < 0x20:
			l.Pos = i
			l.Fail("unescaped control character in string")
			return ""
		}
	}
	l.Pos = len(l.Data)
	l.Fail("unterminated string")
	return ""
}

func (l *Lexer) retainString(value []byte) string {
	if l.Err != nil {
		return ""
	}
	start := l.strings.Len()
	_, _ = l.strings.Write(value)
	return l.strings.String()[start:]
}

// KeyString returns the next object key as a retained string, for map keys.
func (l *Lexer) KeyString() string {
	s := l.String()
	l.Colon()
	return s
}

func (l *Lexer) StringSlow() []byte {
	buf := make([]byte, 0, 64)
	for l.Pos < len(l.Data) {
		c := l.Data[l.Pos]
		if c == '"' {
			l.Pos++
			return bytes.ToValidUTF8(buf, []byte(string(utf8.RuneError)))
		}
		if c != '\\' {
			if c < 0x20 {
				l.Fail("unescaped control character in string")
				return nil
			}
			buf = append(buf, c)
			l.Pos++
			continue
		}
		l.Pos++
		if l.Pos >= len(l.Data) {
			break
		}
		esc := l.Data[l.Pos]
		l.Pos++
		switch esc {
		case '"', '\\', '/':
			buf = append(buf, esc)
		case 'b':
			buf = append(buf, '\b')
		case 'f':
			buf = append(buf, '\f')
		case 'n':
			buf = append(buf, '\n')
		case 'r':
			buf = append(buf, '\r')
		case 't':
			buf = append(buf, '\t')
		case 'u':
			r := rune(l.Hex4())
			if l.Err != nil {
				return nil
			}
			if r >= 0xD800 && r <= 0xDBFF {
				if l.Pos+1 < len(l.Data) && l.Data[l.Pos] == '\\' && l.Data[l.Pos+1] == 'u' {
					l.Pos += 2
					r2 := rune(l.Hex4())
					if r2 >= 0xDC00 && r2 <= 0xDFFF {
						r = utf16.DecodeRune(r, r2)
					} else {
						buf = utf8.AppendRune(buf, utf8.RuneError)
						r = r2
					}
				} else {
					r = utf8.RuneError
				}
			} else if r >= 0xDC00 && r <= 0xDFFF {
				r = utf8.RuneError
			}
			buf = utf8.AppendRune(buf, r)
		default:
			l.Fail("invalid escape")
			return nil
		}
	}
	l.Fail("unterminated string")
	return nil
}

func (l *Lexer) Hex4() uint32 {
	if l.Pos+4 > len(l.Data) {
		l.Fail("invalid \\u escape")
		return 0
	}
	var r uint32
	for i := range 4 {
		c := l.Data[l.Pos+i]
		switch {
		case c >= '0' && c <= '9':
			r = r<<4 | uint32(c-'0')
		case c >= 'a' && c <= 'f':
			r = r<<4 | uint32(c-'a'+10)
		case c >= 'A' && c <= 'F':
			r = r<<4 | uint32(c-'A'+10)
		default:
			l.Fail("invalid \\u escape")
			return 0
		}
	}
	l.Pos += 4
	return r
}

// IsNull consumes a null literal if present. Generated code uses it to match
// encoding/json semantics: null leaves the field untouched.
func (l *Lexer) IsNull() bool {
	if l.Err != nil {
		return false
	}
	l.SkipWS()
	if l.Pos+4 <= len(l.Data) && string(l.Data[l.Pos:l.Pos+4]) == "null" {
		l.Pos += 4
		return true
	}
	return false
}

// NotNull makes the overwhelmingly common compact, non-null path a single
// byte check. It still consumes canonical null and preserves the full
// whitespace/error behavior for every slow path.
func (l *Lexer) NotNull() bool {
	if l.Err != nil {
		return false
	}
	if l.Pos < len(l.Data) && l.Data[l.Pos] > ' ' && l.Data[l.Pos] != 'n' {
		return true
	}
	l.SkipWS()
	if l.Pos+4 <= len(l.Data) && string(l.Data[l.Pos:l.Pos+4]) == "null" {
		l.Pos += 4
		return false
	}
	return true
}

func (l *Lexer) Bool() bool {
	if l.Err != nil {
		return false
	}
	l.SkipWS()
	if l.Pos+4 <= len(l.Data) && string(l.Data[l.Pos:l.Pos+4]) == "true" {
		l.Pos += 4
		return true
	}
	if l.Pos+5 <= len(l.Data) && string(l.Data[l.Pos:l.Pos+5]) == "false" {
		l.Pos += 5
		return false
	}
	l.Fail("expected Bool")
	return false
}

// Number returns one syntactically valid JSON number without converting it.
func (l *Lexer) Number() []byte {
	if l.Err != nil {
		return nil
	}
	l.SkipWS()
	start := l.Pos
	if l.Pos < len(l.Data) && l.Data[l.Pos] == '-' {
		l.Pos++
	}
	if l.Pos >= len(l.Data) {
		l.Fail("expected number")
		return nil
	}
	if l.Data[l.Pos] == '0' {
		l.Pos++
		if l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			l.Fail("invalid leading zero in number")
			return nil
		}
	} else {
		integerStart := l.Pos
		for l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			l.Pos++
		}
		if l.Pos == integerStart {
			l.Fail("expected number")
			return nil
		}
	}
	if l.Pos < len(l.Data) && l.Data[l.Pos] == '.' {
		l.Pos++
		fractionStart := l.Pos
		for l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			l.Pos++
		}
		if l.Pos == fractionStart {
			l.Fail("missing fraction digits")
			return nil
		}
	}
	if l.Pos < len(l.Data) && (l.Data[l.Pos] == 'e' || l.Data[l.Pos] == 'E') {
		l.Pos++
		if l.Pos < len(l.Data) && (l.Data[l.Pos] == '+' || l.Data[l.Pos] == '-') {
			l.Pos++
		}
		exponentStart := l.Pos
		for l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			l.Pos++
		}
		if l.Pos == exponentStart {
			l.Fail("missing exponent digits")
			return nil
		}
	}
	return l.Data[start:l.Pos]
}

func (l *Lexer) Int(bits int) int64 {
	if l.Err != nil {
		return 0
	}
	l.SkipWS()
	start := l.Pos
	negative := l.Pos < len(l.Data) && l.Data[l.Pos] == '-'
	if negative {
		l.Pos++
	}
	if l.Pos >= len(l.Data) || l.Data[l.Pos] < '0' || l.Data[l.Pos] > '9' {
		l.Fail("expected number")
		return 0
	}
	limit := (uint64(1) << (bits - 1)) - 1
	if negative {
		limit++
	}
	var value uint64
	if l.Data[l.Pos] == '0' {
		l.Pos++
		if l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			l.Fail("invalid leading zero in number")
			return 0
		}
	} else {
		for l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			digit := uint64(l.Data[l.Pos] - '0')
			if value > (limit-digit)/10 {
				l.Fail("integer overflow")
				return 0
			}
			value = value*10 + digit
			l.Pos++
		}
	}
	if l.Pos < len(l.Data) && (l.Data[l.Pos] == '.' || l.Data[l.Pos] == 'e' || l.Data[l.Pos] == 'E') {
		l.Pos = start
		l.Number()
		if l.Err == nil {
			l.Fail("expected integer, found number")
		}
		return 0
	}
	if negative {
		if bits == 64 && value == uint64(1)<<63 {
			return -1 << 63
		}
		return -int64(value)
	}
	return int64(value)
}

func (l *Lexer) Int64() int64 { return l.Int(64) }

func (l *Lexer) Uint(bits int) uint64 {
	if l.Err != nil {
		return 0
	}
	l.SkipWS()
	start := l.Pos
	if l.Pos >= len(l.Data) || l.Data[l.Pos] < '0' || l.Data[l.Pos] > '9' {
		l.Fail("expected unsigned integer")
		return 0
	}
	limit := ^uint64(0)
	if bits < 64 {
		limit = (uint64(1) << bits) - 1
	}
	var value uint64
	if l.Data[l.Pos] == '0' {
		l.Pos++
		if l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			l.Fail("invalid leading zero in number")
			return 0
		}
	} else {
		for l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			digit := uint64(l.Data[l.Pos] - '0')
			if value > (limit-digit)/10 {
				l.Fail("integer overflow")
				return 0
			}
			value = value*10 + digit
			l.Pos++
		}
	}
	if l.Pos < len(l.Data) && (l.Data[l.Pos] == '.' || l.Data[l.Pos] == 'e' || l.Data[l.Pos] == 'E') {
		l.Pos = start
		l.Number()
		if l.Err == nil {
			l.Fail("expected unsigned integer")
		}
		return 0
	}
	return value
}

func (l *Lexer) Uint64() uint64 { return l.Uint(64) }

func (l *Lexer) Float(bits int) float64 {
	if l.Err != nil {
		return 0
	}
	l.SkipWS()
	start := l.Pos
	negative := l.Pos < len(l.Data) && l.Data[l.Pos] == '-'
	if negative {
		l.Pos++
	}
	if l.Pos >= len(l.Data) || l.Data[l.Pos] < '0' || l.Data[l.Pos] > '9' {
		l.Fail("expected number")
		return 0
	}

	const exactIntegerLimit = uint64(1) << 52
	fast := true
	var integer uint64
	if l.Data[l.Pos] == '0' {
		l.Pos++
		if l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			l.Fail("invalid leading zero in number")
			return 0
		}
	} else {
		for l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			digit := uint64(l.Data[l.Pos] - '0')
			if fast && integer <= (exactIntegerLimit-digit)/10 {
				integer = integer*10 + digit
			} else {
				fast = false
			}
			l.Pos++
		}
	}

	var fraction uint64
	fractionDigits := 0
	if l.Pos < len(l.Data) && l.Data[l.Pos] == '.' {
		l.Pos++
		fractionStart := l.Pos
		for l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			if fractionDigits < 18 {
				fraction = fraction*10 + uint64(l.Data[l.Pos]-'0')
			} else {
				fast = false
			}
			fractionDigits++
			l.Pos++
		}
		if l.Pos == fractionStart {
			l.Fail("missing fraction digits")
			return 0
		}
	}
	if l.Pos < len(l.Data) && (l.Data[l.Pos] == 'e' || l.Data[l.Pos] == 'E') {
		fast = false
		l.Pos++
		if l.Pos < len(l.Data) && (l.Data[l.Pos] == '+' || l.Data[l.Pos] == '-') {
			l.Pos++
		}
		exponentStart := l.Pos
		for l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			l.Pos++
		}
		if l.Pos == exponentStart {
			l.Fail("missing exponent digits")
			return 0
		}
	}

	if fast {
		if value, ok := decimalFloatParts(integer, fraction, fractionDigits, bits == 64); ok {
			if negative {
				value = -value
			}
			if bits == 32 {
				return float64(float32(value))
			}
			return value
		}
	}
	value, err := strconv.ParseFloat(string(l.Data[start:l.Pos]), bits)
	if err != nil {
		l.Fail("floating-point overflow")
		return 0
	}
	return value
}

func decimalFloatParts(integer, fraction uint64, digits int, allowRoundedDecimal bool) (float64, bool) {
	if digits == 0 {
		return float64(integer), true
	}
	powerFive := uint64(1)
	for range digits {
		powerFive *= 5
	}
	if fraction%powerFive != 0 {
		if !allowRoundedDecimal {
			return 0, false
		}
		powerTen := powerFive * (uint64(1) << digits)
		if powerTen > 1<<52 || integer > ((uint64(1)<<52)-fraction)/powerTen {
			return 0, false
		}
		return float64(integer*powerTen+fraction) / float64(powerTen), true
	}
	return float64(integer) + float64(fraction/powerFive)/float64(uint64(1)<<digits), true
}

func (l *Lexer) Float64() float64 { return l.Float(64) }
func (l *Lexer) Float32() float32 { return float32(l.Float(32)) }

func (l *Lexer) quotedBytes() ([]byte, bool) {
	raw := l.StringBytes()
	if l.Err != nil || string(raw) == "null" {
		return nil, false
	}
	return raw, true
}

func (l *Lexer) failQuoted() {
	l.Fail("invalid use of ,string struct tag")
}

func (l *Lexer) QuotedString() (string, bool) {
	raw, ok := l.quotedBytes()
	if !ok {
		return "", false
	}
	if len(raw) == 0 || raw[0] != '"' {
		l.failQuoted()
		return "", false
	}
	inner := Lexer{Data: raw}
	value := inner.String()
	if inner.Err != nil || inner.Pos != len(inner.Data) {
		l.failQuoted()
		return "", false
	}
	return value, true
}

func (l *Lexer) QuotedBool() (bool, bool) {
	raw, ok := l.quotedBytes()
	if !ok {
		return false, false
	}
	switch string(raw) {
	case "true":
		return true, true
	case "false":
		return false, true
	default:
		l.failQuoted()
		return false, false
	}
}

func (l *Lexer) QuotedInt(bits int) (int64, bool) {
	raw, ok := l.quotedBytes()
	if !ok {
		return 0, false
	}
	if len(raw) == 0 || raw[0] != '-' && (raw[0] < '0' || raw[0] > '9') {
		l.failQuoted()
		return 0, false
	}
	value, err := strconv.ParseInt(string(raw), 10, bits)
	if err != nil {
		l.failQuoted()
		return 0, false
	}
	return value, true
}

func (l *Lexer) QuotedUint(bits int) (uint64, bool) {
	raw, ok := l.quotedBytes()
	if !ok {
		return 0, false
	}
	if len(raw) == 0 || raw[0] < '0' || raw[0] > '9' {
		l.failQuoted()
		return 0, false
	}
	value, err := strconv.ParseUint(string(raw), 10, bits)
	if err != nil {
		l.failQuoted()
		return 0, false
	}
	return value, true
}

func (l *Lexer) QuotedFloat(bits int) (float64, bool) {
	raw, ok := l.quotedBytes()
	if !ok {
		return 0, false
	}
	if len(raw) == 0 || raw[0] != '-' && (raw[0] < '0' || raw[0] > '9') {
		l.failQuoted()
		return 0, false
	}
	value, err := strconv.ParseFloat(string(raw), bits)
	if err != nil {
		l.failQuoted()
		return 0, false
	}
	return value, true
}

// SkipValue validates and advances past one JSON value of any shape.
func (l *Lexer) SkipValue() {
	l.skipValue(0)
}

func (l *Lexer) skipValue(depth int) {
	if l.Err != nil {
		return
	}
	l.SkipWS()
	if l.Pos >= len(l.Data) {
		l.Fail("unexpected end of input")
		return
	}
	switch l.Data[l.Pos] {
	case '"':
		l.StringBytes()
	case '{':
		if l.Depth+uint64(depth)+1 > l.depthLimit() {
			l.Fail("maximum nesting depth exceeded")
			return
		}
		l.Pos++
		for first := true; l.MoreObject(first); first = false {
			l.KeyBytes()
			l.skipValue(depth + 1)
		}
	case '[':
		if l.Depth+uint64(depth)+1 > l.depthLimit() {
			l.Fail("maximum nesting depth exceeded")
			return
		}
		l.Pos++
		for first := true; l.MoreArray(first); first = false {
			l.skipValue(depth + 1)
		}
	case 't':
		l.Literal("true")
	case 'f':
		l.Literal("false")
	case 'n':
		l.Literal("null")
	default:
		l.Number()
	}
}

func (l *Lexer) Literal(want string) {
	if l.Err != nil {
		return
	}
	if len(l.Data)-l.Pos < len(want) || string(l.Data[l.Pos:l.Pos+len(want)]) != want {
		l.Fail("invalid literal")
		return
	}
	l.Pos += len(want)
}

// RawValue returns the raw bytes of the next value, for encoding/json
// fallbacks on field types the generator does not handle natively.
func (l *Lexer) RawValue() []byte {
	if l.Err != nil {
		return nil
	}
	l.SkipWS()
	start := l.Pos
	l.SkipValue()
	if l.Err != nil {
		return nil
	}
	return l.Data[start:l.Pos]
}

const jsonHexDigits = "0123456789abcdef"

func IntSize(value int64) int {
	if value < 0 {
		if value == -1<<63 {
			return 20
		}
		return UintSize(uint64(-value)) + 1
	}
	return UintSize(uint64(value))
}

func UintSize(value uint64) int {
	size := 1
	for value >= 10 {
		value /= 10
		size++
	}
	return size
}

func AppendString(dst []byte, s string) []byte {
	dst = append(dst, '"')
	start := 0
	for i := 0; i < len(s); {
		c := s[i]
		if c < utf8.RuneSelf {
			if c >= 0x20 && c != '"' && c != '\\' && c != '<' && c != '>' && c != '&' {
				i++
				continue
			}
			dst = append(dst, s[start:i]...)
			switch c {
			case '"', '\\':
				dst = append(dst, '\\', c)
			case '\b':
				dst = append(dst, '\\', 'b')
			case '\f':
				dst = append(dst, '\\', 'f')
			case '\n':
				dst = append(dst, '\\', 'n')
			case '\r':
				dst = append(dst, '\\', 'r')
			case '\t':
				dst = append(dst, '\\', 't')
			default:
				dst = append(dst, '\\', 'u', '0', '0', jsonHexDigits[c>>4], jsonHexDigits[c&0xF])
			}
			i++
			start = i
			continue
		}

		r, size := utf8.DecodeRuneInString(s[i:])
		if r == utf8.RuneError && size == 1 {
			dst = append(dst, s[start:i]...)
			dst = append(dst, `\ufffd`...)
			i++
			start = i
			continue
		}
		if r == '\u2028' || r == '\u2029' {
			dst = append(dst, s[start:i]...)
			dst = append(dst, '\\', 'u', '2', '0', '2', byte('8'+r-'\u2028'))
			i += size
			start = i
			continue
		}
		i += size
	}
	dst = append(dst, s[start:]...)
	return append(dst, '"')
}

func AppendFloat(dst []byte, value float64, bits int) ([]byte, error) {
	if math.IsNaN(value) || math.IsInf(value, 0) {
		return nil, fmt.Errorf("json: unsupported value: %v", value)
	}
	return strconv.AppendFloat(dst, value, 'g', -1, bits), nil
}

func AppendBytes(dst, value []byte) []byte {
	if value == nil {
		return append(dst, "null"...)
	}
	dst = append(dst, '"')
	dst = base64.StdEncoding.AppendEncode(dst, value)
	return append(dst, '"')
}

func AppendRaw(dst, value []byte) ([]byte, error) {
	if value == nil {
		return append(dst, "null"...), nil
	}
	l := Lexer{Data: value}
	dst = appendRawValue(dst, &l, 0)
	if l.Err != nil {
		return nil, l.Err
	}
	l.SkipWS()
	if l.Pos != len(l.Data) {
		return nil, fmt.Errorf("json: trailing data at offset %d", l.Pos)
	}
	return dst, nil
}

func appendRawValue(dst []byte, l *Lexer, depth int) []byte {
	if l.Err != nil {
		return dst
	}
	l.SkipWS()
	if l.Pos >= len(l.Data) {
		l.Fail("unexpected end of input")
		return dst
	}
	switch l.Data[l.Pos] {
	case '"':
		return AppendString(dst, l.String())
	case '{':
		if l.Depth+uint64(depth)+1 > l.depthLimit() {
			l.Fail("maximum nesting depth exceeded")
			return dst
		}
		l.Pos++
		dst = append(dst, '{')
		for first := true; l.MoreObject(first); first = false {
			if !first {
				dst = append(dst, ',')
			}
			dst = AppendString(dst, l.KeyString())
			dst = append(dst, ':')
			dst = appendRawValue(dst, l, depth+1)
		}
		return append(dst, '}')
	case '[':
		if l.Depth+uint64(depth)+1 > l.depthLimit() {
			l.Fail("maximum nesting depth exceeded")
			return dst
		}
		l.Pos++
		dst = append(dst, '[')
		for first := true; l.MoreArray(first); first = false {
			if !first {
				dst = append(dst, ',')
			}
			dst = appendRawValue(dst, l, depth+1)
		}
		return append(dst, ']')
	case 't':
		l.Literal("true")
		return append(dst, "true"...)
	case 'f':
		l.Literal("false")
		return append(dst, "false"...)
	case 'n':
		l.Literal("null")
		return append(dst, "null"...)
	default:
		raw := l.Number()
		return append(dst, raw...)
	}
}

func (l *Lexer) Bytes() []byte {
	if l.IsNull() {
		return nil
	}
	l.SkipWS()
	if l.Pos < len(l.Data) && l.Data[l.Pos] == '[' {
		value := make([]byte, 0, 8)
		l.ArrayOpen()
		for first := true; l.MoreArray(first); first = false {
			if l.IsNull() {
				value = append(value, 0)
				continue
			}
			decoded := l.Uint(8)
			if l.Err != nil {
				return nil
			}
			value = append(value, byte(decoded))
		}
		return value
	}
	raw := l.StringBytes()
	if l.Err != nil {
		return nil
	}
	value, err := base64.StdEncoding.DecodeString(string(raw))
	if err != nil {
		l.Fail("invalid base64 data")
		return nil
	}
	return value
}
