// Code generated by metago; DO NOT EDIT.

package jsonruntime

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"math"
	"strconv"
	"unicode/utf16"
	"unicode/utf8"
)

// Lexer is a cursor over the input buffer. All methods are no-ops after
// the first error, so generated code never checks errors mid-parse.
type Lexer struct {
	Data []byte
	// Text is a lazily created string copy of Data. Retained strings are
	// substrings of it, so a whole parse costs one string allocation instead
	// of one per value. The trade-off: any retained string pins the full copy.
	Text string
	Pos  int
	Err  error
}

func (l *Lexer) Fail(msg string) {
	if l.Err == nil {
		l.Err = fmt.Errorf("json: %s at offset %d", msg, l.Pos)
	}
}

func (l *Lexer) SkipWS() {
	for l.Pos < len(l.Data) {
		c := l.Data[l.Pos]
		if c != ' ' && c != '\t' && c != '\n' && c != '\r' {
			return
		}
		l.Pos++
	}
}

// Expect takes the failure message as a caller-provided constant so the
// success path never builds a string.
func (l *Lexer) Expect(c byte, what string) {
	if l.Err != nil {
		return
	}
	l.SkipWS()
	if l.Pos < len(l.Data) && l.Data[l.Pos] == c {
		l.Pos++
		return
	}
	l.Fail("expected " + what)
}

func (l *Lexer) ObjectOpen() { l.Expect('{', "'{'") }
func (l *Lexer) ArrayOpen()  { l.Expect('[', "'['") }

func (l *Lexer) MoreObject(first bool) bool {
	return l.More(first, '}')
}

func (l *Lexer) MoreArray(first bool) bool {
	return l.More(first, ']')
}

func (l *Lexer) More(first bool, close byte) bool {
	if l.Err != nil {
		return false
	}
	l.SkipWS()
	if l.Pos >= len(l.Data) {
		l.Fail("unexpected end of input")
		return false
	}
	if l.Data[l.Pos] == close {
		l.Pos++
		return false
	}
	if !first {
		if l.Data[l.Pos] != ',' {
			l.Fail("expected ','")
			return false
		}
		l.Pos++
		l.SkipWS()
		if l.Pos < len(l.Data) && l.Data[l.Pos] == close {
			l.Fail("trailing comma")
			return false
		}
	}
	return true
}

// KeyBytes returns the next object key. The result may alias the input buffer.
func (l *Lexer) KeyBytes() []byte {
	b := l.StringBytes()
	l.Expect(':', "':'")
	return b
}

// StringBytes parses a JSON string. Unescaped valid UTF-8 aliases the input;
// escaped or malformed UTF-8 input is normalized into a new buffer.
func (l *Lexer) StringBytes() []byte {
	if l.Err != nil {
		return nil
	}
	l.SkipWS()
	if l.Pos >= len(l.Data) || l.Data[l.Pos] != '"' {
		l.Fail("expected string")
		return nil
	}
	l.Pos++
	start := l.Pos
	quote := bytes.IndexByte(l.Data[l.Pos:], '"')
	if quote < 0 {
		l.Fail("unterminated string")
		return nil
	}
	plain := l.Data[l.Pos : l.Pos+quote]
	if bytes.IndexByte(plain, '\\') < 0 {
		for _, c := range plain {
			if c < 0x20 {
				l.Fail("unescaped control character in string")
				return nil
			}
		}
		l.Pos += quote + 1
		if utf8.Valid(plain) {
			return l.Data[start : start+quote]
		}
		return bytes.ToValidUTF8(plain, []byte(string(utf8.RuneError)))
	}
	return l.StringSlow()
}

// String returns a parsed string that is safe to retain after the parse.
func (l *Lexer) String() string {
	return string(l.StringBytes())
}

// KeyString returns the next object key as a retained string, for map keys.
func (l *Lexer) KeyString() string {
	s := l.String()
	l.Expect(':', "':'")
	return s
}

func (l *Lexer) StringSlow() []byte {
	buf := make([]byte, 0, 64)
	for l.Pos < len(l.Data) {
		c := l.Data[l.Pos]
		if c == '"' {
			l.Pos++
			return bytes.ToValidUTF8(buf, []byte(string(utf8.RuneError)))
		}
		if c != '\\' {
			if c < 0x20 {
				l.Fail("unescaped control character in string")
				return nil
			}
			buf = append(buf, c)
			l.Pos++
			continue
		}
		l.Pos++
		if l.Pos >= len(l.Data) {
			break
		}
		esc := l.Data[l.Pos]
		l.Pos++
		switch esc {
		case '"', '\\', '/':
			buf = append(buf, esc)
		case 'b':
			buf = append(buf, '\b')
		case 'f':
			buf = append(buf, '\f')
		case 'n':
			buf = append(buf, '\n')
		case 'r':
			buf = append(buf, '\r')
		case 't':
			buf = append(buf, '\t')
		case 'u':
			r := rune(l.Hex4())
			if l.Err != nil {
				return nil
			}
			if r >= 0xD800 && r <= 0xDBFF {
				if l.Pos+1 < len(l.Data) && l.Data[l.Pos] == '\\' && l.Data[l.Pos+1] == 'u' {
					l.Pos += 2
					r2 := rune(l.Hex4())
					if r2 >= 0xDC00 && r2 <= 0xDFFF {
						r = utf16.DecodeRune(r, r2)
					} else {
						buf = utf8.AppendRune(buf, utf8.RuneError)
						r = r2
					}
				} else {
					r = utf8.RuneError
				}
			} else if r >= 0xDC00 && r <= 0xDFFF {
				r = utf8.RuneError
			}
			buf = utf8.AppendRune(buf, r)
		default:
			l.Fail("invalid escape")
			return nil
		}
	}
	l.Fail("unterminated string")
	return nil
}

func (l *Lexer) Hex4() uint32 {
	if l.Pos+4 > len(l.Data) {
		l.Fail("invalid \\u escape")
		return 0
	}
	var r uint32
	for i := range 4 {
		c := l.Data[l.Pos+i]
		switch {
		case c >= '0' && c <= '9':
			r = r<<4 | uint32(c-'0')
		case c >= 'a' && c <= 'f':
			r = r<<4 | uint32(c-'a'+10)
		case c >= 'A' && c <= 'F':
			r = r<<4 | uint32(c-'A'+10)
		default:
			l.Fail("invalid \\u escape")
			return 0
		}
	}
	l.Pos += 4
	return r
}

// IsNull consumes a null literal if present. Generated code uses it to match
// encoding/json semantics: null leaves the field untouched.
func (l *Lexer) IsNull() bool {
	if l.Err != nil {
		return false
	}
	l.SkipWS()
	if l.Pos+4 <= len(l.Data) && string(l.Data[l.Pos:l.Pos+4]) == "null" {
		l.Pos += 4
		return true
	}
	return false
}

func (l *Lexer) Bool() bool {
	if l.Err != nil {
		return false
	}
	l.SkipWS()
	if l.Pos+4 <= len(l.Data) && string(l.Data[l.Pos:l.Pos+4]) == "true" {
		l.Pos += 4
		return true
	}
	if l.Pos+5 <= len(l.Data) && string(l.Data[l.Pos:l.Pos+5]) == "false" {
		l.Pos += 5
		return false
	}
	l.Fail("expected Bool")
	return false
}

// Number returns one syntactically valid JSON number without converting it.
func (l *Lexer) Number() []byte {
	if l.Err != nil {
		return nil
	}
	l.SkipWS()
	start := l.Pos
	if l.Pos < len(l.Data) && l.Data[l.Pos] == '-' {
		l.Pos++
	}
	if l.Pos >= len(l.Data) {
		l.Fail("expected number")
		return nil
	}
	if l.Data[l.Pos] == '0' {
		l.Pos++
		if l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			l.Fail("invalid leading zero in number")
			return nil
		}
	} else {
		integerStart := l.Pos
		for l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			l.Pos++
		}
		if l.Pos == integerStart {
			l.Fail("expected number")
			return nil
		}
	}
	if l.Pos < len(l.Data) && l.Data[l.Pos] == '.' {
		l.Pos++
		fractionStart := l.Pos
		for l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			l.Pos++
		}
		if l.Pos == fractionStart {
			l.Fail("missing fraction digits")
			return nil
		}
	}
	if l.Pos < len(l.Data) && (l.Data[l.Pos] == 'e' || l.Data[l.Pos] == 'E') {
		l.Pos++
		if l.Pos < len(l.Data) && (l.Data[l.Pos] == '+' || l.Data[l.Pos] == '-') {
			l.Pos++
		}
		exponentStart := l.Pos
		for l.Pos < len(l.Data) && l.Data[l.Pos] >= '0' && l.Data[l.Pos] <= '9' {
			l.Pos++
		}
		if l.Pos == exponentStart {
			l.Fail("missing exponent digits")
			return nil
		}
	}
	return l.Data[start:l.Pos]
}

func (l *Lexer) Int(bits int) int64 {
	raw := l.Number()
	if l.Err != nil {
		return 0
	}
	for _, c := range raw {
		if c == '.' || c == 'e' || c == 'E' {
			l.Fail("expected integer, found number")
			return 0
		}
	}
	n, err := strconv.ParseInt(string(raw), 10, bits)
	if err != nil {
		l.Fail("integer overflow")
		return 0
	}
	return n
}

func (l *Lexer) Int64() int64 { return l.Int(64) }

func (l *Lexer) Uint(bits int) uint64 {
	raw := l.Number()
	if l.Err != nil {
		return 0
	}
	for _, c := range raw {
		if c == '-' || c == '.' || c == 'e' || c == 'E' {
			l.Fail("expected unsigned integer")
			return 0
		}
	}
	n, err := strconv.ParseUint(string(raw), 10, bits)
	if err != nil {
		l.Fail("integer overflow")
		return 0
	}
	return n
}

func (l *Lexer) Uint64() uint64 { return l.Uint(64) }

func (l *Lexer) Float(bits int) float64 {
	raw := l.Number()
	if l.Err != nil {
		return 0
	}
	f, err := strconv.ParseFloat(string(raw), bits)
	if err != nil {
		l.Fail("floating-point overflow")
		return 0
	}
	return f
}

func (l *Lexer) Float64() float64 { return l.Float(64) }
func (l *Lexer) Float32() float32 { return float32(l.Float(32)) }

const maxJSONDepth = 10000

// SkipValue validates and advances past one JSON value of any shape.
func (l *Lexer) SkipValue() {
	l.skipValue(0)
}

func (l *Lexer) skipValue(depth int) {
	if l.Err != nil {
		return
	}
	if depth >= maxJSONDepth {
		l.Fail("maximum nesting depth exceeded")
		return
	}
	l.SkipWS()
	if l.Pos >= len(l.Data) {
		l.Fail("unexpected end of input")
		return
	}
	switch l.Data[l.Pos] {
	case '"':
		l.StringBytes()
	case '{':
		l.Pos++
		for first := true; l.MoreObject(first); first = false {
			l.KeyBytes()
			l.skipValue(depth + 1)
		}
	case '[':
		l.Pos++
		for first := true; l.MoreArray(first); first = false {
			l.skipValue(depth + 1)
		}
	case 't':
		l.Literal("true")
	case 'f':
		l.Literal("false")
	case 'n':
		l.Literal("null")
	default:
		l.Number()
	}
}

func (l *Lexer) Literal(want string) {
	if l.Err != nil {
		return
	}
	if len(l.Data)-l.Pos < len(want) || string(l.Data[l.Pos:l.Pos+len(want)]) != want {
		l.Fail("invalid literal")
		return
	}
	l.Pos += len(want)
}

// RawValue returns the raw bytes of the next value, for encoding/json
// fallbacks on field types the generator does not handle natively.
func (l *Lexer) RawValue() []byte {
	if l.Err != nil {
		return nil
	}
	l.SkipWS()
	start := l.Pos
	l.SkipValue()
	if l.Err != nil {
		return nil
	}
	return l.Data[start:l.Pos]
}

const jsonHexDigits = "0123456789abcdef"

func AppendString(dst []byte, s string) []byte {
	dst = append(dst, '"')
	start := 0
	for i := 0; i < len(s); {
		c := s[i]
		if c < utf8.RuneSelf {
			if c >= 0x20 && c != '"' && c != '\\' && c != '<' && c != '>' && c != '&' {
				i++
				continue
			}
			dst = append(dst, s[start:i]...)
			switch c {
			case '"', '\\':
				dst = append(dst, '\\', c)
			case '\b':
				dst = append(dst, '\\', 'b')
			case '\f':
				dst = append(dst, '\\', 'f')
			case '\n':
				dst = append(dst, '\\', 'n')
			case '\r':
				dst = append(dst, '\\', 'r')
			case '\t':
				dst = append(dst, '\\', 't')
			default:
				dst = append(dst, '\\', 'u', '0', '0', jsonHexDigits[c>>4], jsonHexDigits[c&0xF])
			}
			i++
			start = i
			continue
		}

		r, size := utf8.DecodeRuneInString(s[i:])
		if r == utf8.RuneError && size == 1 {
			dst = append(dst, s[start:i]...)
			dst = append(dst, `\ufffd`...)
			i++
			start = i
			continue
		}
		if r == '\u2028' || r == '\u2029' {
			dst = append(dst, s[start:i]...)
			dst = append(dst, '\\', 'u', '2', '0', '2', byte('8'+r-'\u2028'))
			i += size
			start = i
			continue
		}
		i += size
	}
	dst = append(dst, s[start:]...)
	return append(dst, '"')
}

func AppendFloat(dst []byte, value float64, bits int) ([]byte, error) {
	if math.IsNaN(value) || math.IsInf(value, 0) {
		return nil, fmt.Errorf("json: unsupported value: %v", value)
	}
	return strconv.AppendFloat(dst, value, 'g', -1, bits), nil
}

func AppendBytes(dst, value []byte) []byte {
	if value == nil {
		return append(dst, "null"...)
	}
	dst = append(dst, '"')
	dst = base64.StdEncoding.AppendEncode(dst, value)
	return append(dst, '"')
}

func (l *Lexer) Bytes() []byte {
	if l.IsNull() {
		return nil
	}
	raw := l.StringBytes()
	if l.Err != nil {
		return nil
	}
	value, err := base64.StdEncoding.DecodeString(string(raw))
	if err != nil {
		l.Fail("invalid base64 data")
		return nil
	}
	return value
}
