baseURL = "https://metago.dev/"
locale = "en-US"
title = "Metago"
disableKinds = ["taxonomy", "term"]
enableGitInfo = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = "assets/notwatching/hugo_stats\\.json"
    target = "css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    disableWatch = true
    source = "hugo_stats.json"
    target = "assets/notwatching/hugo_stats.json"

[params]
  description = "Metaprogramming for Go, using Go."
  github = "https://github.com/guillemus/metago"

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = false
  [markup.goldmark.renderer]
    unsafe = true
